// Generated by claude-workspace/scripts/italy_build_places_food_apps.py
window.FOOD=[
{
"stop": 1,
"area": "Rome — Termini night (Sep 29)",
"restaurants": [
{
"name": "Mercato Centrale Roma (food hall inside Termini station)",
"address": "Via Giovanni Giolitti 36, 00185 Roma",
"order": "Pick from the stalls: a trapizzino (pizza-bread pocket filled with Roman stew) at Stefano Callegari's counter, fried Roman snacks from Arcangelo Dandini's fry counter, pizza from Luca Mastracci, then gelato (Paolo Pomposi) or a Neapolitan sfogliatella (Sabato Sessa). Stall list from Mercato Centrale's own site.",
"price": "€ — you pay stall by stall (exact prices not published)",
"closed": "Open every day, 7:30–23:30 (official site)",
"booking": "no — walk in; shared tables",
"why": "About 2 minutes from the guesthouse, open late every night, no booking — the easy choice after a travel day.",
"sources": [
"https://www.mercatocentrale.com/rome/artisans/",
"https://www.mercatocentrale.com/rome/info/"
],
"section": null
},
{
"name": "Trattoria Monti",
"address": "Via di San Vito 13/A, 00185 Roma",
"order": "Tortello al rosso d'uovo — one giant raviolo filled with ricotta, spinach and a runny egg yolk (the house signature); olive all'ascolana (fried stuffed olives); coniglio in porchetta (stuffed rabbit). Per Katie Parla and Gambero Rosso.",
"price": "€€ — about €50 per person (Gambero Rosso average)",
"closed": "Sunday evening and all day Monday, so it is open on Tuesday 29 Sep. Also closes in August and for short spells in April and December.",
"booking": "yes — essential; small room of about 45 seats. Phone +39 06 446 6573",
"why": "About 5 min walk; a family-run trattoria for decades, cooking Le Marche and Roman dishes, loved by locals and guidebooks alike.",
"sources": [
"https://www.gamberorosso.it/luoghi/locali/trattoria/trattoria-monti/",
"https://katieparla.com/trattoria-monti-rome/"
],
"section": null
},
{
"name": "Trattoria Da Danilo",
"address": "Via Petrarca 13, 00185 Roma",
"order": "Tonnarelli cacio e pepe, tossed at your table inside a wheel of pecorino (€14); 'Sua Maestà la Carbonara' (€14); coda alla vaccinara, oxtail stew (€18). Dishes and prices from the restaurant's own menu; Time Out calls the carbonara one of the best in the city.",
"price": "€€–€€€ — pasta €14–16, main courses €16–28, cover charge €2.50 (restaurant's own menu)",
"closed": "Sunday all day and Monday lunch — open for dinner on Tuesday 29 Sep",
"booking": "advised — phone +39 06 7720 0111 or book online through the restaurant's website",
"why": "About 10–12 min walk past Piazza Vittorio; a classic Roman trattoria famous for its table-side cacio e pepe — the 'nicer' dinner of the three.",
"sources": [
"https://www.trattoriadadanilo.com/menu-alla-carta/",
"https://www.timeout.com/rome/restaurants/trattoria-da-danilo"
],
"section": null
}
],
"foods_to_try": [
{
"food": "cacio e pepe",
"what": "Pasta tossed with pecorino romano cheese and lots of black pepper — no cream."
},
{
"food": "carbonara",
"what": "Pasta with egg yolk, crisp guanciale (cured pork cheek), pecorino and black pepper — again, no cream."
},
{
"food": "amatriciana",
"what": "Pasta in a tomato sauce with guanciale and pecorino."
},
{
"food": "gricia",
"what": "Guanciale, pecorino and black pepper — like an amatriciana without the tomato."
},
{
"food": "supplì",
"what": "A fried rice croquette with tomato sauce and a melting mozzarella centre."
},
{
"food": "trapizzino",
"what": "A triangle of pizza bread split open and filled with a Roman stew such as chicken cacciatora or meatballs."
},
{
"food": "olive all'ascolana",
"what": "Big green olives stuffed with meat, breaded and fried — a Le Marche speciality you will find at Trattoria Monti."
}
]
},
{
"stop": 2,
"area": "Castiglione del Lago — Lake Trasimeno (Sep 30 – Oct 5)",
"restaurants": [
{
"name": "L'Acquario",
"address": "Via Vittorio Emanuele 69, 06061 Castiglione del Lago (PG)",
"order": "Oven-roasted porchetta-style 'queen carp' medallion (medaglione di carpa regina porchettato) - the dish Michelin singles out; also tegamaccio lake-fish stew and dishes with Trasimeno fagiolina beans (The Wom Travel, Aug 2026). The menu is built on lake carp, perch, eel and tench from the local fishing co-op (restaurant website).",
"price": "€€ - about €30-40 per person (Restaurant Guru)",
"closed": "No lunch on Tuesday or Wednesday - dinner only those days (Michelin hours). The restaurant's own website says 'closed Wednesdays', so phone +39 075 965 2432 before going on a Wednesday.",
"booking": "advised",
"why": "Michelin Bib Gourmand 2026 (good food at fair prices) in the old town, about 0.9 km uphill walk from Le Macerine - the best place to try lake fish done properly.",
"sources": [
"https://guide.michelin.com/it/it/umbria/castiglione-del-lago/ristorante/l-acquario",
"https://travel.thewom.it/italia/umbria/ristoranti-sul-lago-trasimeno.html"
],
"section": null
},
{
"name": "La Cantina",
"address": "Via Vittorio Emanuele 93, 06061 Castiglione del Lago (PG)",
"order": "Carpa regina in porchetta (porchetta-style lake carp with vegetables, €16.50), maltagliati pasta with tench fillets and Trasimeno fagiolina beans (€14), pici with Chianina beef ragù and aged pecorino (€13) - from the restaurant's current online menu. Wood-oven pizza too.",
"price": "€€ - pastas €10-14, mains €16.50-20; roughly €25-40 per person",
"closed": "Open every day, 10:00-23:00 (restaurant contacts page)",
"booking": "advised",
"why": "Long-running family restaurant (over 50 years, per its website) on the old town's main street, about 0.9 km uphill walk from Le Macerine; open daily, so a safe pick for the arrival night (Wed 30 Sep).",
"sources": [
"https://menu.ristorantecantina.it/",
"https://www.ristorantecantina.it/contacts/?lang=en"
],
"section": null
},
{
"name": "La Terrazza",
"address": "Via Vittorio Emanuele 45, 06061 Castiglione del Lago (PG)",
"order": "From its 'lake specialties' menu (March 2026): tegamaccio del Trasimeno lake-fish soup (€22), carpa regina in porchetta (€20), gnocchetti with lake perch and black truffle (€20 - the dish reviewers mention most), fagiolina beans with perch fillet (€16).",
"price": "€€ (upper end) - about €35-50 per person; pastas €15-25, mains €18-25, cover €3",
"closed": "Tuesday (Restaurant Guru)",
"booking": "advised - ask for a terrace table with the lake view",
"why": "The nicer dinner for this stop: bright dining room and panoramic terrace over the lake in the old town, about 0.75 km walk from Le Macerine.",
"sources": [
"https://www.ilristorantelaterrazza.it/wp-content/uploads/2026/03/menu-ristoranteLaTerrazza-web.pdf",
"https://restaurantguru.com/Caffe-Latino-Castiglione-del-Lago"
],
"section": null
},
{
"name": "Lido Solitario",
"address": "Via Lungolago 16, 06061 Castiglione del Lago (PG)",
"order": "Fritto misto di lago (fried lake fish, €20), perch parmigiana (€16), tench croquettes with sauces (€10.50), pici with a lake-fish tomato sauce (€14.50) - from the August 2026 menu; also known for pizza alla pala (long rectangular pizza).",
"price": "€-€€ - about €20-35 per person; cover €2.50",
"closed": "Open every day, lunch and dinner (restaurant website)",
"booking": "advised",
"why": "Relaxed trattoria right on the lakeshore with big windows and a terrace, about 300 m from the ferry pier to the islands; about 1.1 km walk from Le Macerine.",
"sources": [
"https://lidosolitario.it/en/",
"https://lidosolitario.it/wp-content/uploads/2026/08/Men%C3%B9-2026-rev-01_26-Lido-Solitario-11ago26.pdf"
],
"section": null
},
{
"name": "Osteria Le Scalette",
"address": "Via XXV Aprile 24/a, 06061 Castiglione del Lago (PG)",
"order": "Ravioli filled with Pienza pecorino in a white Cinta Senese pork ragù, wild boar stew (bocconcini di cinghiale), venison, hand-rolled pasta and lake fish - the dishes recent reviewers single out (Sluurpy review roundup).",
"price": "€ - about €20-30 per person (Restaurant Guru)",
"closed": "Thursday; Monday lunch only (Restaurant Guru)",
"booking": "advised - small place",
"why": "Small husband-and-wife osteria a stone's throw from the old town, with a lake-view terrace and generous home cooking at low prices; about 0.75 km walk from Le Macerine.",
"sources": [
"https://www.sluurpy.it/castiglione-del-lago/ristorante/83694/osteria-le-scalette/recensioni",
"https://restaurantguru.com/Le-Scalette-Castiglione-del-Lago"
],
"section": null
},
{
"name": "Scuola Elementare della Pasta",
"address": "Via Vittorio Emanuele 32, 06061 Castiglione del Lago (PG)",
"order": "Fresh pasta made by hand in front of you (tagliatelle, gnocchi, truffle pasta) and certified Chianina beef as steak or carpaccio - per the owners' website and the dishes reviewers mention most.",
"price": "€ - about €20-30 per person (Restaurant Guru)",
"closed": "No closing day listed - open daily for lunch and dinner (Restaurant Guru)",
"booking": "advised",
"why": "Easygoing old-town spot where you watch the pasta being made as you walk in; about 0.75 km walk from Le Macerine.",
"sources": [
"https://barbiniheritage.com/en/palazzo-barbini-city-hotel/ristorante-scuola-elementare-della-pasta",
"https://restaurantguru.com/Scuola-Elementare-della-Pasta-Castiglione-del-Lago"
],
"section": null
},
{
"name": "La Bucaccia (Cortona)",
"address": "Via Ghibellina 17, 52044 Cortona (AR)",
"order": "'Bringoli' (Cortona's hand-rolled pici pasta) tossed inside a whole pecorino cheese wheel at the table - the house signature on its own menu page; also Romano's aged pecorino cheeses and the tartare section Michelin mentions. A set 'Michelin menu' is €29 per person (starter, pasta, main, side, dessert; the whole table must order it).",
"price": "€ - Michelin '€'; set menu €29 per person, drinks extra",
"closed": "Monday (Michelin; the restaurant's site says Mondays in winter)",
"booking": "yes - the restaurant says booking is required",
"why": "Cortona lunch, Thu 1 Oct: Michelin Bib Gourmand 2026 in a 13th-century palazzo with small rustic rooms; owner Romano is famously entertaining.",
"sources": [
"https://guide.michelin.com/it/it/toscana/cortona/ristorante/la-bucaccia",
"https://www.labucaccia.it/en/the-menu"
],
"section": null
},
{
"name": "Trattoria Pallotta (Assisi)",
"address": "Vicolo della Volta Pinta 3 (off Piazza del Comune), 06081 Assisi (PG)",
"order": "Strangozzi (Umbrian homemade pasta) with mushroom sauce, torta al testo (griddle flatbread), rabbit alla cacciatora, homemade tagliatelle or gnocchi, zuppa inglese for dessert - dishes listed on its own website.",
"price": "€€ - about €30-40 per person (Restaurant Guru)",
"closed": "Tuesday (restaurant website)",
"booking": "yes - by WhatsApp or SMS only, +39 370 369 8913 (restaurant website); Assisi will be busy because 4 Oct is the Feast of St Francis",
"why": "Assisi lunch, Sat 3 Oct: family trattoria since 1860, through the painted 'Volta Pinta' archway just off the main square - simple, seasonal Umbrian cooking.",
"sources": [
"https://www.trattoriapallotta.it/",
"https://restaurantguru.com/Trattoria-Pallotta-Assisi"
],
"section": null
},
{
"name": "Da Sauro (Isola Maggiore)",
"address": "Via Guglielmi 1, 06069 Isola Maggiore, Tuoro sul Trasimeno (PG)",
"order": "Lake fish: tegamaccio (lake-fish stew), carpa regina in porchetta, perch fillet with butter and sage, tagliolini with carp roe or smoked tench - all on its own menu.",
"price": "€ - about €22-31 per person (Restaurant Guru)",
"closed": "No weekly closing day listed. October opening could NOT be confirmed online - phone +39 075 826168 before the boat trip.",
"booking": "advised - and call to confirm it is open",
"why": "Isola Maggiore lunch, Sun 4 Oct: hotel-restaurant at the end of the fishing village with a lakeside garden and terrace; the island's best-reviewed place (4.8 on Restaurant Guru, about 1,800 reviews). Backup on the island: L'Oso, Via Guglielmi 39 (lunch; +39 075 825 4255).",
"sources": [
"https://dasauro.it/en/menu/",
"https://restaurantguru.com/Da-Sauro-Isola-Maggiore"
],
"section": null
}
],
"foods_to_try": [
{
"food": "Tegamaccio",
"what": "Lake Trasimeno fish stew - eel, pike and perch slow-cooked in a clay pot with tomato and a little chilli, served on garlic toast."
},
{
"food": "Carpa regina in porchetta",
"what": "'Queen carp' from the lake stuffed with wild fennel and bacon and roasted like porchetta - the lake's signature main course."
},
{
"food": "Brustico",
"what": "Lake fishermen's dish (Trasimeno and nearby Lake Chiusi): whole perch or pike blackened over burning reeds, then dressed with olive oil, lemon, salt and pepper."
},
{
"food": "Fagiolina del Trasimeno",
"what": "Tiny, thin-skinned heirloom beans grown around the lake; a Slow Food Presidium since 2000."
},
{
"food": "Torta al testo",
"what": "Umbrian flatbread baked on a hot griddle stone, split and filled with ham, sausage or cooked greens."
},
{
"food": "Strangozzi",
"what": "Umbria's chewy homemade pasta strips, often served with mushrooms, black truffle or a spicy tomato sauce."
},
{
"food": "Pici (bringoli) all'aglione",
"what": "Thick hand-rolled spaghetti with a mild garlic-and-tomato sauce - the Cortona and Val di Chiana classic."
},
{
"food": "Chianina beef",
"what": "Beef from the big white cattle of the Val di Chiana below Cortona - order it as steak, tartare or ragù."
}
]
},
{
"stop": 3,
"area": "Montecatini Terme (Oct 5–10)",
"restaurants": [
{
"name": "Antica Osteria Toscana",
"address": "Via Solferino 12, 51016 Montecatini Terme (PT)",
"order": "Bistecca alla fiorentina and other grilled cuts aged in its own cellar, plus house pastas such as pappardelle with wild boar, pici, and ribollita (restaurant website); reviewers also praise the crostini and pappardelle al ragù.",
"price": "€€ - about €30-80 per person depending on the steak (Restaurant Guru); steak is priced by weight",
"closed": "Open every day, 12:00-14:30 and 18:30-23:00 (restaurant website)",
"booking": "advised",
"why": "The steak dinner: meat-focused Tuscan osteria about 0.9 km walk from Hygge House, open all week.",
"sources": [
"https://www.anticaosteriatoscana.it/montecatini/dove-siamo.asp",
"https://restaurantguru.com/Antica-Osteria-Toscana-Montecatini-Terme"
],
"section": null
},
{
"name": "Trattoria Da Gina",
"address": "Via Puglie 7, 51016 Montecatini Terme (PT)",
"order": "Pappardelle al cinghiale (wild boar), rosticciana (pork ribs), Tuscan antipasto and tiramisu - the most-mentioned dishes on Restaurant Guru; grilled meat is the house specialty (Voloscontato).",
"price": "€ - about €18-30 per person",
"closed": "Tuesday and Wednesday; lunch hours vary, dinner is the safe bet (Restaurant Guru)",
"booking": "yes - popular with locals",
"why": "Homely, good-value trattoria rated 4.7 on Google from about 2,600 reviews; about 1.6 km from Hygge House, so a short taxi for the parents.",
"sources": [
"https://restaurantguru.com/Trattoria-da-Gina-Montecatini-Terme",
"https://www.voloscontato.it/altro/montecatini-terme-dove-mangiare-bene-spendendo-poco.php"
],
"section": null
},
{
"name": "La Pecora Nera",
"address": "Via San Martino 18, 51016 Montecatini Terme (PT) - inside Hotel Ercolini & Savi",
"order": "Champagne risotto with saffron and Parmesan mousse (€20; also praised by the Accademia Italiana della Cucina), the house 'Pecora Nera' fish soup (€30), fresh pici with hand-chopped veal ragù (€26) - from the August 2026 menu.",
"price": "€€€ - about €55-75 per person (pastas €20-30, mains €24-35)",
"closed": "No closing day - dinner nightly 19:00-22:30; lunch on Sundays only (restaurant website)",
"booking": "yes - the restaurant strongly recommends booking",
"why": "The one nicer dinner here: elegant hotel restaurant with a terrace, Tuscan and seafood cooking and a 250-label wine list; about 0.9 km walk from Hygge House.",
"sources": [
"https://www.ristorantelapecoranera.it/en",
"https://accademiaitalianadellacucina.it/it/ristoranti/ristorante/3411-pecora-nera"
],
"section": null
},
{
"name": "Caffè Giusti dal 1898 (Montecatini Alto)",
"address": "Piazza Giuseppe Giusti 24, 51016 Montecatini Alto (Montecatini Terme, PT)",
"order": "Tuscan classics: bistecca alla fiorentina, handmade ravioli and pici, wild boar pasta, ribollita and farro soup, fettunta (garlic bread with olive oil) - dishes named in reviews and listings; house-made gelato.",
"price": "€€ - about €20-60 per person (Restaurant Guru)",
"closed": "Wednesday (Restaurant Guru and Wanderlog; a few listings say open daily)",
"booking": "advised - ask for a table out on the piazza",
"why": "Historic café-restaurant on Montecatini Alto's main square. Go up by the funicular (2026 season to 1 Nov, 9:30-24:00, every 30 min, €7.50 return); the lower station is about 1.9 km from Hygge House.",
"sources": [
"https://montecatini-alto.it/ristoranti/",
"https://restaurantguru.com/Ristorante-Giusti-Montecatini-Terme-2"
],
"section": null
},
{
"name": "La Torre (Montecatini Alto)",
"address": "Piazza Giuseppe Giusti 8, 51016 Montecatini Alto (Montecatini Terme, PT)",
"order": "Traditional Tuscan menu (soups, homemade pasta, meat); reviewers most often mention steak, pasta and polenta - no single signature dish found.",
"price": "€€ - about €30-60 per person (Restaurant Guru)",
"closed": "Tuesday (Restaurant Guru; Mycia menu page)",
"booking": "advised",
"why": "Second choice on the same hilltop piazza, named after the medieval Signorelli tower; useful on Wednesday when Caffè Giusti is closed.",
"sources": [
"https://montecatini-alto.it/ristoranti/la-torre/",
"https://restaurantguru.com/Ristorante-La-Torre-Montecatini-Terme"
],
"section": null
},
{
"name": "Mordi e Fuggi",
"address": "Corso Roma 76, 51016 Montecatini Terme (PT)",
"order": "Neapolitan-style pizza - the house specialty praised in reviews (it also serves sushi).",
"price": "€ - about €10-20 per person (Restaurant Guru)",
"closed": "Monday; dinner only, 19:00-23:00 (restaurant page)",
"booking": "no - casual pizzeria",
"why": "Easy low-key night: good-value pizza only about 300 m (4-5 min walk) from Hygge House.",
"sources": [
"https://mordiefuggimontecatiniterme.eatbu.com/?lang=en",
"https://restaurantguru.com/Mordi-e-Fuggi-Montecatini-Terme"
],
"section": null
},
{
"name": "Buca di Sant'Antonio (Lucca)",
"address": "Via della Cervia 3, 55100 Lucca (LU)",
"order": "Tordelli lucchesi al sugo (Lucca's meat-filled pasta in meat ragù) and capretto (roast kid) - the dishes reviewers mention most (Restaurant Guru); Michelin notes the meat dishes and the fresh pasta rolled out by hand.",
"price": "€€ - about €30-60 per person (Restaurant Guru)",
"closed": "Monday and Sunday (Restaurant Guru; the restaurant's own site says Sunday evening and Monday) - open Tuesday lunch",
"booking": "advised",
"why": "Lucca lunch, Tue 6 Oct: a city classic for over 200 years, copper pots hanging from the ceiling, steps from Piazza San Michele; Michelin-listed.",
"sources": [
"https://guide.michelin.com/it/it/toscana/lucca/ristorante/buca-di-sant-antonio",
"https://restaurantguru.com/Buca-di-SantAntonio-Lucca"
],
"section": null
},
{
"name": "Del Fagioli (Florence)",
"address": "Corso dei Tintori 47r, 50122 Firenze (FI)",
"order": "Per Michelin: bistecca alla fiorentina, pici all'aglione, pappa al pomodoro, 'rifatta' beef cutlet with green beans, and homemade cantucci to finish.",
"price": "€ - about €20-40 per person; CASH ONLY (Restaurant Guru)",
"closed": "Saturday and Sunday",
"booking": "yes - Michelin says to book well ahead",
"why": "Florence lunch, Wed 7 Oct: much-loved, old-school trattoria with a family feel, about 400 m (5 min walk) from the Uffizi; Michelin-listed.",
"sources": [
"https://guide.michelin.com/it/it/toscana/firenze/ristorante/del-fagioli",
"https://restaurantguru.com/Del-Fagioli-Florence"
],
"section": null
},
{
"name": "Osteria dei Cavalieri (Pisa)",
"address": "Via San Frediano 16, 56126 Pisa (PI)",
"order": "Tagliatelline with rabbit and asparagus (€17), wild boar in Chianti with grilled polenta (€19), Tuscan-style tripe (€18), pecorino-and-pepper ravioli with white beans (€18) - from its current menu.",
"price": "€€ - about €35-50 per person; water, cover and service €3.50",
"closed": "Sunday and Wednesday (Restaurant Guru); an older guide listed Saturday lunch and Sunday - Thursday lunch is open either way",
"booking": "advised - by phone only, +39 050 580858 (no email bookings)",
"why": "Pisa lunch, Thu 8 Oct: osteria recommended in past editions of Slow Food's Osterie d'Italia, in a 13th-century tower house about 700 m (9-10 min walk) from the Leaning Tower, away from the tourist traps.",
"sources": [
"https://www.osteriacavalieri.pisa.it/menu/",
"https://restaurantguru.com/Osteria-dei-Cavalieri-Pisa"
],
"section": null
}
],
"foods_to_try": [
{
"food": "Cialde di Montecatini",
"what": "Paper-thin round wafers sandwiching crushed almonds, made in town since 1936 - Bargilli sells them on Viale Verdi 92 and Viale Grocco 2."
},
{
"food": "Bistecca alla fiorentina",
"what": "Thick T-bone steak grilled over coals and served rare, priced by weight (usually 1 kg or more, for two)."
},
{
"food": "Ribollita",
"what": "Thick 'reboiled' Tuscan soup of bread, beans and black cabbage."
},
{
"food": "Pappa al pomodoro",
"what": "Soft, spoonable soup of stale bread, ripe tomato, basil and olive oil."
},
{
"food": "Tordelli lucchesi",
"what": "Lucca's pasta parcels filled with mixed meats, thyme and nutmeg, always served with meat ragù."
},
{
"food": "Buccellato di Lucca",
"what": "Lucca's sweet ring-shaped loaf with raisins and aniseed - a breakfast or teatime treat."
},
{
"food": "Cecina",
"what": "Pisa's thin, crispy chickpea-flour flatbread from a wood oven, eaten hot with black pepper, often in a sandwich."
},
{
"food": "Lampredotto",
"what": "Florence's street-food sandwich of slow-cooked beef tripe with green sauce, sold from kiosks."
}
]
},
{
"stop": 4,
"area": "Montesilvano / Pescara (Oct 10–14)",
"restaurants": [
{
"name": "Taverna 58",
"address": "Corso Manthonè 46, 65127 Pescara",
"order": "Fellata abruzzese (board of local cured meats, pecorino and pâté), the 'frittatina' (single omelette with vegetables and warm goat's cheese), ciammariche (land snails from nearby Città Sant'Angelo, baked with herbs), arrosticini, and soft parrozzo (Pescara's almond cake) for dessert. Dishes per the Michelin Guide, the restaurant's own site and Passione Gourmet (Feb 2024).",
"price": "€ (Michelin's budget band) — about €35 à la carte; lunch menu €18 (Passione Gourmet, Feb 2024)",
"closed": "All day Sunday, plus Friday and Saturday lunch (restaurant's site). So: Sat 10 Oct dinner only, closed Sun 11, open Mon 12 and Tue 13 for lunch and dinner.",
"booking": "advised — +39 085 690724",
"why": "Pescara's classic Abruzzese trattoria since 1980, in the old quarter where D'Annunzio was born; Michelin Bib Gourmand (good value) and a Slow Food 'snail' in the 2026 osterie guide.",
"sources": [
"https://guide.michelin.com/us/en/abruzzo/pescara/restaurant/taverna-58",
"https://www.taverna58.it/",
"https://passionegourmet.it/2024/02/01/taverna-58/"
],
"section": null
},
{
"name": "Estrò – Il Bistrot con l'accento",
"address": "Piazza della Rinascita 23 (Piazza Salotto), 65122 Pescara",
"order": "Octopus 'alla marinara' — cooked in two stages and served with cherry tomatoes, garlic, olives and capers; it is the dish the Michelin inspectors single out. The chef also leans to meat (e.g. Black Angus carpaccio, per Scatti di Gusto). A recent diner recommends the 5-course tasting menu at €45 (Restaurant Guru).",
"price": "€ (Michelin's budget band); 5-course tasting menu €45",
"closed": "Listings disagree: Wednesday (Restaurant Guru) or Thursday (Italia.it). Either way it is open Sat 10 to Tue 13, lunch and dinner.",
"booking": "advised — only a few tables inside and on the square; +39 085 62388",
"why": "Michelin Bib Gourmand bistro with a terrace on Pescara's main square; good-value fish and meat cooking in a relaxed setting.",
"sources": [
"https://guide.michelin.com/us/en/abruzzo/pescara/restaurant/estro",
"https://restaurantguru.com/Estro-Il-Bistrot-Con-LAccento-Pescara",
"https://www.italia.it/en/abruzzo/pescara/where-to-eat/estro-il-bistrot-con-laccento"
],
"section": null
},
{
"name": "Da Bacone",
"address": "Lungomare Giacomo Matteotti 54, 65121 Pescara",
"order": "Brodetto alla pescarese (Pescara's fish stew), the mixed seafood antipasto, and home-made pasta with seafood — per Gambero Rosso.",
"price": "€€ — about €30–50 per person (Restaurant Guru)",
"closed": "All day Monday and Sunday evening (open Sunday lunch). Tue–Sat lunch and dinner.",
"booking": "advised — +39 085 421 2280",
"why": "Beachfront restaurant of the Romano family, fishermen for generations; Gambero Rosso (June 2024) calls it a reliable, far-from-ordinary seaside kitchen. Reviews run through September 2026 and December 2025, so it stays open outside summer.",
"sources": [
"https://www.gamberorosso.it/ristoranti/dove-mangiare-mare-pescara-ristoranti/",
"https://restaurantguru.com/Da-Bacone-Pescara-3"
],
"section": null
},
{
"name": "La Pecorella",
"address": "Via Gabriele D'Annunzio 57, 65015 Montesilvano",
"order": "Arrosticini: home-made, hand-cut and 'delicious in the liver version too', says Gambero Rosso; also mixed boards of cured meats, tagliata (sliced steak) and griddled cheese.",
"price": "€ — about €20–30 per person (Restaurant Guru)",
"closed": "Monday. Evenings only, Tue–Sun from about 5 pm (Restaurant Guru). So: good for Sat 10, Sun 11 or Tue 13 dinner.",
"booking": "advised — +39 328 809 4038",
"why": "Small family-run arrosticini house in central Montesilvano near the town hall, so no train needed; on Gambero Rosso's October 2024 list of the best arrosticini around Pescara.",
"sources": [
"https://www.gamberorosso.it/rubriche/miniguide/dove-mangiare-arrosticini-pescara/",
"https://restaurantguru.com/La-Pecorella-Pescara",
"https://www.abruzzocitta.it/lapecorella/"
],
"section": null
},
{
"name": "Da Carletto",
"address": "Corso Umberto I 167, 65015 Montesilvano",
"order": "The house 'spaghetto alla Carletto', fettuccine al Montepulciano with squid and scampi, seafood salad and mixed fried fish (most-mentioned dishes on Sluurpy); the restaurant's own site also lists raw-fish platters and linguine with lemon, prawns and tuna tartare.",
"price": "€€ — about €30–40 per person (Sluurpy)",
"closed": "Monday; Sunday lunch only (restaurant's site: Tue–Sat 10:00–23:00, Sun 10:00–15:00).",
"booking": "advised — +39 085 445 1597",
"why": "Seafood restaurant and fish deli since 1999 on the same street as your hotel (Corso Umberto I) — an easy dinner with no train. Well reviewed through late 2025.",
"sources": [
"https://www.dacarletto.it/",
"https://www.sluurpy.it/montesilvano/ristorante/27323/da-carletto"
],
"section": null
},
{
"name": "Trabocco Punta Cavalluccio",
"address": "Contrada Piane Favaro 267 (SS16 coast road, around km 486), 66020 Rocca San Giovanni (CH) — between San Vito Chietino and Fossacesia",
"order": "Fixed seafood menu based on the day's catch — typically octopus salad, sagnette with 'pelosi' (small rock crabs), fried squid and anchovies, stuffed mussels and peppered mussels (restaurant's own site).",
"price": "€€€ — fixed menu €70 per person, wine extra (own site)",
"closed": "Open every day for lunch and dinner from April to October; closed November–March (own site). Scatti di Gusto gives the season as April to late October, so Mon 12 Oct should be open.",
"booking": "yes — essential, seats are limited. Call Tommaso Verì +39 338 598 0985 (or +39 333 301 0800) and reconfirm the day before: bad weather can close a trabocco.",
"why": "Trabocco lunch for Mon 12 Oct (car day): a wooden fishing platform over the sea, run by the same family for over a century; in Scatti di Gusto's top-10 trabocchi (updated Sept 2026). This lunch is effectively the area's one splurge meal.",
"sources": [
"https://www.traboccopuntacavalluccio.it/en/",
"https://www.scattidigusto.it/10-migliori-trabocchi-ristoranti-mare-abruzzo"
],
"section": null
},
{
"name": "Trabocco Valle Grotte",
"address": "Località Fosso Canale 1 (SS16 Adriatica km 482.5), 66038 San Vito Chietino (CH)",
"order": "Fixed seafood menu: welcome aperitivo, hot and cold starters, pasta, fish main with a side, dessert and coffee (own site). Scatti di Gusto singles out the paccheri with seafood ragù; the site also names tacconcelli with tuna and sea bass with potatoes.",
"price": "€€€ — fixed menu €70 per person including water and cover charge; wine extra (own site)",
"closed": "Open every day for lunch and dinner from April to October (own site).",
"booking": "yes — the restaurant says a phone confirmation is essential: +39 338 186 6074",
"why": "Second trabocco option for Mon 12 Oct, right at San Vito Chietino; also in Scatti di Gusto's top-10 trabocchi (updated Sept 2026).",
"sources": [
"https://www.traboccovallegrotte.com/ristorante/",
"https://www.scattidigusto.it/10-migliori-trabocchi-ristoranti-mare-abruzzo"
],
"section": null
},
{
"name": "La Bilancia (Hotel Ristorante) — Loreto Aprutino option",
"address": "Contrada Palazzo 11, 65014 Loreto Aprutino (PE) — in the countryside, about 10 minutes' drive from the old town",
"order": "Pasta alla mugnaia, the house speciality (dressed with garlic, oil and dried chilli); ravioli filled with sheep's-milk ricotta; potato gnocchi with goat sauce; meats and cheese grilled over an oak wood fire (restaurant's own site).",
"price": "€–€€ — about €22–44 per person (Restaurant Guru)",
"closed": "Monday and Sunday evening. Open Tue 13 Oct for lunch, 12:00–14:30 (MyCIA menu listing).",
"booking": "advised — +39 085 828 9321",
"why": "Lunch for Tue 13 Oct if you go to Loreto Aprutino: family trattoria since 1974 with a Slow Food 'snail' in the 2026 osterie guide. It is outside town, so you would need a taxi or lift from Loreto.",
"sources": [
"https://www.hotellabilancia.it/",
"https://www.ilcentro.it/pescara/osterie-ditalia-quattordici-le-chiocciole-per-labruzzo-llmammia",
"https://www.mycia.it/menu/loreto-aprutino/hotel-ristorante-la-bilancia-T7gbwncym",
"https://www.booking.com/hotel/it/ristorante-la-bilancia.html"
],
"section": null
},
{
"name": "Osteria del Leone — Penne option",
"address": "Piazza XX Settembre 3, 65017 Penne (PE) — in the old town",
"order": "Home-made pasta: ravioli with saffron cream, ravioli cacio e pepe and pappardelle 'campagnole', plus tagliata (sliced steak) — the dishes most mentioned in recent reviews (Sluurpy, Dec 2025). The Touring Club listing also names pasta alla mugnaia with wild boar and borage, and braised lamb with roasted peppers.",
"price": "€–€€ — about €20–30 per person (Sluurpy); Restaurant Guru says €30–40",
"closed": "Monday (one listing also says Sunday). Open Tue 13 Oct for lunch, roughly 12:00/12:30–14:00; on Tuesdays and Wednesdays it serves lunch only (Restaurant Guru).",
"booking": "advised for lunch — +39 085 821 3224",
"why": "Lunch for Tue 13 Oct if you go to Penne: a simple Abruzzese osteria with a brick-vaulted room right in the old town, so no taxi needed.",
"sources": [
"https://www.touringclub.it/destinazioni/penne/mangiare/118589-osteria-del-leone",
"https://restaurantguru.com/Del-Leone-Penne",
"https://www.sluurpy.it/penne/ristorante/86981/osteria-del-leone"
],
"section": null
}
],
"foods_to_try": [
{
"food": "Arrosticini",
"what": "Little skewers of mutton or lamb grilled over charcoal and eaten by the handful; the liver ones (di fegato) are a local favourite."
},
{
"food": "Brodetto alla pescarese",
"what": "Pescara's fish stew: several kinds of Adriatic fish slow-cooked in a sauce coloured red with sweet dried peppers — mop it up with bread."
},
{
"food": "Pallotte cacio e ova",
"what": "Balls of cheese and egg, fried and then simmered in tomato sauce — 'meatballs' without the meat."
},
{
"food": "Maccheroni (spaghetti) alla chitarra",
"what": "Square-edged egg pasta cut on a wire-strung frame called a 'guitar', usually served with a meat ragù."
},
{
"food": "Pasta alla mugnaia",
"what": "Thick home-made pasta you'll find around Penne and Loreto Aprutino, dressed with garlic, oil and chilli or with a meat sauce."
},
{
"food": "Sagnette con i pelosi",
"what": "Short flat pasta in a sauce of small rock crabs — a dish of the trabocchi coast."
},
{
"food": "Parrozzo",
"what": "Pescara's dome-shaped almond cake coated in dark chocolate."
},
{
"food": "Montepulciano d'Abruzzo and Cerasuolo",
"what": "The region's everyday red wine, and its deep-pink rosé cousin made from the same grape."
}
]
},
{
"stop": 5,
"area": "Lecce (Oct 14–21)",
"restaurants": [
{
"name": "Alle Due Corti",
"address": "Corte dei Giugni 1 (corner of Via L. Prato 42), 73100 Lecce",
"order": "Crema di fave con cicoria (broad-bean purée with wild chicory), lagane e ceci (pasta with chickpeas), orecchiette with turnip tops, cucole (aubergine 'meatballs'), lasagna 'ncannulata and lamb with onions — all named by Gambero Rosso (Oct 2023).",
"price": "€–€€ — one 2023 review paid €45 for two pastas, a main, a dessert, water and a quarter-litre of wine (Sluurpy)",
"closed": "Sunday. Mon–Sat lunch (about 12:20–14:00) and dinner (about 19:20–22:30), per the restaurant's site.",
"booking": "advised — phone +39 0832 242223 (the site says same-day bookings are not taken by email)",
"why": "Gambero Rosso's pick if you want a traditional Lecce trattoria: menu written in Salento dialect, hand-made pasta, mostly country dishes. In the old town, facing the Arco di Prato.",
"sources": [
"https://www.gamberorosso.it/ristoranti/dove-mangiare-lecce-migliori-ristoranti-secondo-gambero-rosso/",
"https://alleduecorti.com/reloaded/index.php/contatti/",
"https://www.arte.it/guida-arte/lecce/in-citta/ristorante/alle-due-corti-antica-gastronomia-salentina-2944"
],
"section": null
},
{
"name": "Le Zie – Cucina Casareccia",
"address": "Via Colonnello Archimede Costadura 19, 73100 Lecce — just outside the old-town walls",
"order": "Ciceri e tria (pasta and chickpeas with crisp fried pasta), tiella/tajeddhra (baked mussels with potatoes, courgettes and rice), octopus cooked in a clay pot, stuffed squid, pittule (fried dough balls) and the cassata cake for dessert — from Il Gourmet Errante, Food Me Tender and recent Sluurpy reviews.",
"price": "€ — about €20–30 per person (Sluurpy)",
"closed": "All day Monday and Sunday evening (open Tue–Sat lunch and dinner, Sunday lunch).",
"booking": "yes — book by phone: +39 0832 245178. Reviewers say booking is required and a table may be given away if you are late.",
"why": "Home-style family trattoria that feels like lunch at an aunt's house — a Slow Food 'snail' in the 2026 osterie guide.",
"sources": [
"https://www.dissapore.com/ristoranti/le-migliori-osterie-ditalia-del-2026-regione-per-regione/",
"https://www.sluurpy.it/lecce/ristorante/95236/trattoria-le-zie-cucina-casareccia",
"https://www.ilgourmeterrante.it/sito/osteria-zie-lecce/"
],
"section": null
},
{
"name": "Mezzo Quinto Osteria",
"address": "Piazzetta Giuseppe Verdi 5, 73100 Lecce — by the old-town walls",
"order": "Salento home cooking: ciceri e tria or orecchiette, fave e cicorie (broad-bean purée with chicory), cocule (potato fritters), pezzetti di cavallo (horse-meat stew), and 'torta pasticciotto' with custard and sour cherries for dessert (Gambero Rosso, March 2025).",
"price": "€ — about €22 per person on average (TheFork)",
"closed": "Monday, and no lunch on Sunday (lunch Tue–Sat 12:00–15:00, dinner Tue–Sun 19:00–24:00, per its own site).",
"booking": "yes — the restaurant asks for reservations: +39 328 088 2474 or +39 0832 198 7544",
"why": "Opened in 2025 by the team behind Mezzo Quinto, Gambero Rosso's best street food in Puglia (2023); Gambero Rosso called it the typical trattoria Lecce was missing. Quiet little square, very good value, reviews into 2026.",
"sources": [
"https://www.gamberorosso.it/attualita/apre-trattoria-quinto-osteria-lecce/",
"https://www.mezzoquintolecce.com/sedi/",
"https://www.thefork.it/ristorante/mezzo-quinto-osteria-r838525"
],
"section": null
},
{
"name": "Caffè Alvino",
"address": "Piazza Sant'Oronzo 30, 73100 Lecce",
"order": "Breakfast: a warm pasticciotto with a caffè leccese (iced espresso with almond milk); later in the day, a hot rustico leccese — baked several times a day and 'among the best in town' (Gambero Rosso).",
"price": "€ — café prices (exact prices not published)",
"closed": "The city tourism site (Visit Lecce) lists it open daily 7:00–24:00; one other online listing says closed Tuesday.",
"booking": "no — walk in; outdoor tables on the square",
"why": "Lecce's historic café (a century old in 2022) facing the Roman amphitheatre — the classic place to try all three Lecce staples in one stop.",
"sources": [
"https://www.gamberorossointernational.com/news/where-to-find-the-best-street-food-in-lecce-including-pucce-pizzi-and-rustici-leccesi/",
"https://visitlecce.eu/it/luogo/caffe-alvino-le-dolci-fantasie"
],
"section": null
},
{
"name": "Pasticceria Natale",
"address": "Via Salvatore Trinchese 7, 73100 Lecce",
"order": "The traditional pasticciotto, the 'fruttone' made with artisan jams, and — as a fun extra — pasticciotto-flavoured gelato (Gambero Rosso).",
"price": "€ — pastries; boxed almond sweets and mustazzoli biscuits from €5 (shop's site)",
"closed": "None listed — online listings show it open every day.",
"booking": "no",
"why": "Historic pastry shop run by Fernando Natale and his wife since the 1970s; on Gambero Rosso's list of the best pasticciotti in Salento.",
"sources": [
"https://www.gamberorosso.it/rubriche/classifiche/dove-trovare-i-migliori-pasticciotti-del-salento/",
"https://natalepasticceria.it/"
],
"section": null
},
{
"name": "L'Angolino di via Matteotti",
"address": "Via Giacomo Matteotti 31, 73100 Lecce (one listing says no. 25) — opposite the MUST city museum, by the Roman theatre",
"order": "Puccia leccese — a soft round bread, hollow inside, filled with as many ingredients as you like; or try it with pezzetti di cavallo, the spicy local horse-meat stew (Gambero Rosso).",
"price": "€ — street-food prices (about €8 a puccia, per one online guide)",
"closed": "None listed — daily 11:30–15:00 and 18:30–24:00 (online listing).",
"booking": "no — small place with outdoor seating",
"why": "Gambero Rosso's pick for puccia in the old town, a few steps from the cathedral — an easy, cheap lunch.",
"sources": [
"https://www.gamberorossointernational.com/news/where-to-find-the-best-street-food-in-lecce-including-pucce-pizzi-and-rustici-leccesi/",
"https://www.oraridiapertura24.it/filiale/Lecce-L%27Angolino%20di%20Via%20Matteotti%20Pucceria%20Tipica%20e%20Cornetteria-1174118J.html",
"https://www.airial.travel/restaurants/italy/lecce/langolino-di-via-matteotti-Y0gn-Hql"
],
"section": null
},
{
"name": "Duo Ristorante",
"address": "Via Giuseppe Garibaldi 11, 73100 Lecce",
"order": "A tasting menu — e.g. 'Sintesi': three courses of your choice plus a welcome from the chef (whole table) — Puglian recipes given a personal, creative twist (Michelin; menu on the restaurant's site).",
"price": "€€€ — about €45–80 per person without drinks (3BonMenu)",
"closed": "Monday and Tuesday. Wed–Sat dinner only (19:30–22:30); Sunday lunch and dinner (restaurant's site).",
"booking": "yes — +39 0832 520956",
"why": "The one nicer dinner for Lecce: Michelin-listed ('Inspector's favourite'), intimate and softly lit; chef Fabiano Viva trained with Michelin-starred chefs.",
"sources": [
"https://guide.michelin.com/us/en/puglia/lecce/restaurant/duo-ristorante",
"https://www.ristoranteduo.it/",
"https://www.3bonmenu.com/785_Duo-Ristorante-di-Fabiano-Viva-Lecce.html"
],
"section": null
},
{
"name": "La Vinaigrette — Gallipoli lunch",
"address": "Riviera Armando Diaz 75, 73014 Gallipoli (LE) — old town, opposite the castle's main entrance",
"order": "Local purple prawns (gambero viola), raw fish carpacci and tartares, swordfish chunks with turnip tops, paccheri with red mullet sauce, and fried squid (Gambero Rosso).",
"price": "€€ — about €30–35 per person without drinks (Luciano Pignataro; TheFork)",
"closed": "Tuesday — so open Fri 16 Oct. Open all year, lunch and dinner.",
"booking": "advised — +39 0833 264501 or WhatsApp +39 349 231 6169",
"why": "Gallipoli lunch (Fri 16 Oct): friendly rustic room with stone vaults plus an outdoor terrace, facing the Angevin castle; on Gambero Rosso's 2024 Gallipoli list, and the website is updated for 2026.",
"sources": [
"https://www.gamberorosso.it/ristoranti/dove-mangiare-gallipoli-ristoranti/",
"https://lavinaigrette.it/",
"https://2night.it/la-vinaigrette-gallipoli.html",
"https://www.lucianopignataro.it/a/trattoria-la-vinaigrette-di-gallipoli/90320/"
],
"section": null
},
{
"name": "Agli Angeli Ribelli — Otranto lunch",
"address": "Via Immacolata 20, 73028 Otranto (LE) — old town",
"order": "Seafood pasta — linguine or orecchiette ai frutti di mare, linguine with mussels cacio e pepe — plus orata all'otrantina (sea bream Otranto-style) and mixed fried fish (most-mentioned dishes on Sluurpy); Restaurant Guru's Otranto guide picks its spaghetti alle vongole.",
"price": "€–€€ — about €20–30 per person (Sluurpy)",
"closed": "Thursday — so open Sat 17 Oct (lunch about 12:00–14:30).",
"booking": "advised on a Saturday",
"why": "Otranto lunch (Sat 17 Oct): relaxed, fairly priced old-town trattoria with castle views, and open through the winter (reviews from December 2025). No major guide lists a budget lunch spot in Otranto, so this pick rests on review sites.",
"sources": [
"https://www.sluurpy.it/otranto/ristorante/30480/agli-angeli-ribelli",
"https://restaurantguru.com/guides/the-best-things-to-eat-in-otranto-italy",
"https://www.wanderlog.com/list/geoCategory/74691/where-to-eat-best-restaurants-in-otranto"
],
"section": null
}
],
"foods_to_try": [
{
"food": "Pasticciotto",
"what": "Oval shortcrust pastry filled with custard — best eaten warm, at breakfast."
},
{
"food": "Rustico leccese",
"what": "Round puff-pastry parcel filled with béchamel, mozzarella and tomato, eaten hot."
},
{
"food": "Puccia",
"what": "Soft round bread, hollow inside, stuffed with fillings you choose — Lecce's favourite sandwich."
},
{
"food": "Caffè leccese",
"what": "Espresso poured over ice with almond milk — Lecce's signature coffee."
},
{
"food": "Ciceri e tria",
"what": "Pasta with chickpeas, with some of the pasta strips fried until crunchy."
},
{
"food": "Fave e cicorie",
"what": "Smooth purée of dried broad beans with boiled wild chicory and olive oil."
},
{
"food": "Pezzetti di cavallo",
"what": "Chunks of horse meat stewed in a spicy tomato sauce — a Lecce classic ('cavallo' on a menu means horse)."
},
{
"food": "Gambero viola di Gallipoli",
"what": "Gallipoli's purple-red prawns, sweet enough to be eaten raw."
}
]
},
{
"stop": 6,
"area": "Salerno (Oct 21–25)",
"restaurants": [
{
"name": "Bistrot di Pescheria",
"address": "Via Luigi Guercio 1 (corner of Via Baratta), 84134 Salerno",
"order": "Squid soup with 'nduja, potato mousse and crispy bread (the Michelin Guide's pick); spaghettoni with mussels and cheese, shrimp croquettes, octopus alla luciana (Luciano Pignataro, December 2025).",
"price": "€€ — about €50 for starter, pasta and dessert (Pignataro, December 2025)",
"closed": "Monday according to Pignataro (December 2025); Michelin lists it as open daily. No Monday falls in your Salerno stay.",
"booking": "yes — advised; it fills up at lunch and dinner. Phone +39 089 209 8475",
"why": "New Michelin Bib Gourmand for 2026 — the more affordable sister of Pescheria, Salerno's best-known fish restaurant; about 10 min walk. Your one 'nicer' seafood dinner.",
"sources": [
"https://guide.michelin.com/us/en/campania/salerno/restaurant/bistrot-di-pescheria",
"https://www.lucianopignataro.it/a/bistrot-di-pescheria-salerno/211587/"
],
"section": null
},
{
"name": "Osteria Canali",
"address": "Via dei Canali 34, 84121 Salerno",
"order": "Maracucciata — a Cilento 'polenta' made from an old local legume — served with escarole; fusilli from Felitto with ragù and cacioricotta cheese (€15); spaghetti with anchovies, capers and olives (€13). Per Scatti di Gusto, February 2026.",
"price": "€€ — about €40 for three hearty dishes (Scatti di Gusto, February 2026)",
"closed": "Open Thursday to Sunday only (Saturday lunch and dinner, Sunday lunch only) according to Scatti di Gusto, February 2026 — closed Monday to Wednesday. Phone to confirm.",
"booking": "advised — phone or WhatsApp +39 339 525 2672",
"why": "Home cooking from the Cilento countryside in the old town near the Duomo; listed in Slow Food's Osterie d'Italia guide 2023–2025 (per the osteria). About 15–20 min walk.",
"sources": [
"https://www.scattidigusto.it/osteria-canali-a-salerno-menu-prezzi-recensione",
"https://www.osteriacanali.com/en/osteria-canali-2/"
],
"section": null
},
{
"name": "Hostaria Il Brigante",
"address": "Via Fratelli Linguiti 4, 84121 Salerno",
"order": "Pasta alla sangiovannara — penne with peppers, aubergine, tomato and provola cheese — the house signature (Touring Club Italiano).",
"price": "€ — about €10–20 per person (Restaurant Guru)",
"closed": "Monday (Restaurant Guru)",
"booking": "advised — small room with shared tables; phone +39 389 262 5756",
"why": "Simple, old-school tavern by the Duomo, with shared tables and brigand-era memorabilia on the walls; one of the cheapest good meals in town. About 15 min walk.",
"sources": [
"https://www.touringclub.it/destinazioni/salerno/mangiare/111281-hostaria-il-brigante",
"https://restaurantguru.com/Hostaria-Il-Brigante-Salerno"
],
"section": null
},
{
"name": "Màdia (pizzeria)",
"address": "Via Irno 2 (inside the Irno Center), 84135 Salerno",
"order": "Margherita (€6); Friggitella (peppers, tomato, sausage and buffalo cheese on a cereal-grain dough); Scarola, fichi e 'nduja (escarole, fig jam and spicy 'nduja). Per Luciano Pignataro, February 2025.",
"price": "€ — Margherita €6 (Pignataro, 2025)",
"closed": "Open every evening from 19:30 (no closing day listed)",
"booking": "advised — online ('Prenota un tavolo' on pizzeriamadia.it) or phone +39 089 286 3178",
"why": "Scored 95 and won a special prize for research and innovation in Gambero Rosso's 2026 pizzeria guide; modern room with well-spaced tables; about 12–15 min walk.",
"sources": [
"https://www.lucianopignataro.it/a/pizzeria-madia-salerno-francesco-miranda/137335/",
"https://www.mangiaredadio.it/guida-pizzerie-ditalia-2026-del-gambero-rosso/"
],
"section": null
},
{
"name": "Antica Dolceria Pantaleone (pastry shop)",
"address": "Via dei Mercanti 75, 84121 Salerno",
"order": "The scazzetta — sponge cake, cream, rum and wild strawberries under a shiny red strawberry glaze, shaped like a cardinal's cap; it was created here (Luciano Pignataro).",
"price": "€ (prices not published)",
"closed": null,
"booking": "no",
"why": "Salerno's most famous pastry shop, founded in 1868 in a former chapel on the old town's main street; about 14 min walk.",
"sources": [
"https://www.lucianopignataro.it/a/la-scazzetta-dellantica-dolceria-pantaleone-a-salerno-assaggi-di-paradiso-tra-sacro-e-profano/158337/",
"https://dolceriapantaleone.it/"
],
"section": null
},
{
"name": "Bar Gelateria Nettuno (seafront gelato)",
"address": "Lungomare Trieste 136/138, 84121 Salerno",
"order": "Brioche con gelato — gelato in a soft brioche bun, their signature since the late 1970s; try the house 'Nocciotella' flavour (Nettuno's own site).",
"price": "€ (prices not published)",
"closed": null,
"booking": "no",
"why": "Seafront gelato institution since 1975, about 8 min walk along the Lungomare — made for the evening stroll.",
"sources": [
"https://www.barnettuno.it/en/history/",
"https://www.lucianopignataro.it/a/mangiare-e-bere-a-salerno-luci-d-artista/60084/"
],
"section": null
},
{
"name": "Tenuta Vannulo — organic buffalo-mozzarella farm (Paestum lunch)",
"address": "Via Galileo Galilei 101, Contrada Vannulo, 84047 Capaccio Paestum (SA)",
"order": "Lunch in the farm's tasting room: organic vegetable starters, a pasta or soup, their own buffalo mozzarella and a homemade dessert (Pignataro, 2021). Buffalo-milk yogurt and puddings at the Yogurteria. A 50-minute morning tour (9:00–12:00) shows the mozzarella being made (farm's own site).",
"price": "€€ — the set lunch was €30–40 per person in 2021 (Pignataro); a mozzarella-only tasting costs less. 2026 prices not found.",
"closed": "Tasting room open daily 12:00–16:00; farm open daily 7:00–19:30; closed 25 Dec, 1 Jan and Easter Sunday (farm's own site)",
"booking": "yes — book the lunch/tasting and any tour ahead: +39 0828 727894 (option 1) or info@vannulo.it; dairy +39 0828 724765",
"why": "Yes, Vannulo is open to visitors and serves lunch. It is about 3 km (straight line) north-east of the temples — take a taxi, it is not a walk.",
"sources": [
"https://www.tenutavannulo.com/en/visita-in-tenuta-2/",
"https://www.lucianopignataro.it/a/ristorante-vannulo-paestum-capaccio/99370/"
],
"section": null
},
{
"name": "La Bettola del Gusto (Pompeii lunch)",
"address": "Via Sacra 48, 80045 Pompei (NA) — the restaurant's own site gives no. 50",
"order": "Spaghettoni di Gragnano with fresh anchovies and Cetara anchovy sauce, the chef's signature (Gazzetta del Gusto, 2024); seasonal seafood pastas and fried salt cod (Scatti di Gusto, 2025).",
"price": "€€ — about €50 for starter, pasta and main (Scatti di Gusto, 2025); tasting menus €45 and €60 (Gazzetta del Gusto, 2024)",
"closed": "Monday (Scatti di Gusto, 2025)",
"booking": "yes — strongly advised; phone +39 081 863 7811 or WhatsApp",
"why": "Slow Food chefs'-alliance kitchen beside Pompei railway station and the Sanctuary, about 7–8 min walk from the ruins' Piazza Anfiteatro entrance.",
"sources": [
"https://www.scattidigusto.it/ristorante-la-bettola-del-gusto-a-pompei",
"https://www.gazzettadelgusto.it/locali/la-bettola-del-gusto-una-tavola-di-qualita-a-pompei/"
],
"section": null
}
],
"foods_to_try": [
{
"food": "mozzarella di bufala",
"what": "Soft, milky fresh cheese made from water-buffalo milk — the plain around Paestum is its heartland."
},
{
"food": "colatura di alici di Cetara",
"what": "A clear, amber anchovy sauce from the fishing village of Cetara, just along the coast, drizzled over spaghetti."
},
{
"food": "alici",
"what": "Fresh local anchovies, served fried or marinated in lemon."
},
{
"food": "pasta alla sangiovannara",
"what": "Penne with peppers, aubergine, tomato and provola cheese — a Salerno dish (try it at Il Brigante)."
},
{
"food": "maracucciata",
"what": "A Cilento 'polenta' made from maracuoccio, an old chickpea-like legume, often served with greens."
},
{
"food": "scazzetta",
"what": "Salerno's own cake — sponge, cream and wild strawberries under a red glaze, shaped like a cardinal's cap."
},
{
"food": "sfogliatella",
"what": "A shell-shaped, crackly pastry filled with sweet ricotta and semolina — Campania's classic breakfast pastry."
},
{
"food": "limoncello",
"what": "Sweet lemon liqueur made from Amalfi Coast lemons, served ice-cold after dinner."
}
]
},
{
"stop": 7,
"area": "Rome — Trastevere week (Oct 25 – Nov 1)",
"restaurants": [
{
"name": "L'Osteria della Trippa",
"address": "Via Goffredo Mameli 15, 00153 Roma",
"order": "Roman pasta classics — carbonara, amatriciana, cacio e pepe — and a crisp fried carciofo alla giudia (artichoke); the adventurous can try the house tripe. Per the Michelin Guide.",
"price": "€€ (Michelin price band)",
"closed": "Sunday. Dinner only Monday–Thursday (18:30–22:30); lunch and dinner Friday–Saturday.",
"booking": "advised — OpenTable, or phone +39 06 4555 4475",
"why": "Michelin Bib Gourmand (good cooking at fair prices) a few minutes' walk from your door.",
"sources": [
"https://guide.michelin.com/us/en/lazio/roma/restaurant/osteria-della-trippa",
"https://www.losteriadellatrippa.it/"
],
"section": null
},
{
"name": "Trattoria Da Teo",
"address": "Piazza dei Ponziani 7/A, 00153 Roma",
"order": "Amatriciana, cacio e pepe, artichokes and fried starters (Gambero Rosso); the coda alla vaccinara (oxtail stew) is also recommended (Food Me Tender, 2023).",
"price": "€€ — about €35–45 per person (Food Me Tender, 2023)",
"closed": "Sunday",
"booking": "yes — strongly advised; phone +39 06 581 8355",
"why": "Family-run local favourite with outdoor tables on a quiet little square; about 12 min walk.",
"sources": [
"https://www.gamberorossointernational.com/news/where-to-eat-in-trastevere-the-historic-district-of-rome-the-definitive-guide/",
"https://www.foodmetender.com/en/favourite-restaurants/trattoria-da-teo-english-review-rome-trastevere/"
],
"section": null
},
{
"name": "La Tavernaccia da Bruno",
"address": "Via Giovanni da Castel Bolognese 63, 00153 Roma",
"order": "Suckling pig roasted in the wood oven with potatoes, lasagna from the wood oven, amatriciana, pappardelle with wild-boar ragù. Per Luciano Pignataro (March 2024).",
"price": "€€ — about €40 per person (Pignataro, 2024)",
"closed": "Wednesday and Thursday (restaurant's website). Open on Sunday — useful for your arrival night, when most Trastevere trattorie are shut.",
"booking": "advised — phone +39 06 581 2792",
"why": "Family trattoria since 1968 with a wood-fired oven; about 20 min walk south, or a short ride on tram 8 to Trastevere station.",
"sources": [
"https://www.lucianopignataro.it/a/roma-osteria-la-tavernaccia/86163/",
"https://www.latavernacciaroma.com/"
],
"section": null
},
{
"name": "Seu Pizza (formerly Seu Pizza Illuminati)",
"address": "Via Angelo Bargoni 10–18, 00153 Roma",
"order": "'La mia Margherita', Super Provola e Pepe, the Genovese (slow-cooked beef and onion) and the fried starters — or one of the set tasting menus (€30–35, €40–45 or €60–65). Per Scatti di Gusto, January 2026.",
"price": "€€ — pizzas €12–20 (Scatti di Gusto, 2026)",
"closed": "Open every evening from 19:00, plus Saturday lunch",
"booking": "yes — advised; online through TheFork on seupizza.com, or phone +39 06 588 3384",
"why": "Ranked the no. 2 pizzeria in Italy by 50 Top Pizza 2026; reopened in October 2025 after a full makeover; about 12 min walk.",
"sources": [
"https://www.scattidigusto.it/seu-pizza-a-roma-trastevere-menu-prezzi-recensione",
"https://www.50toppizza.it/referenza/seu-pizza-illuminati-2026"
],
"section": null
},
{
"name": "Supplì Roma",
"address": "Via di San Francesco a Ripa 137, 00153 Roma",
"order": "The classic supplì (Katie Parla's pick), plus carbonara or cacio e pepe versions and pizza by the slice (shop's own site).",
"price": "€ — street-food prices (exact prices not published)",
"closed": "Sunday",
"booking": "no — walk in",
"why": "Trastevere's classic supplì shop, going since 1979; about 4 min walk — a perfect snack between sights.",
"sources": [
"https://katieparla.com/where-to-and-drink-eat-in-trastevere-rome/",
"https://www.suppliroma.it/?lang=en"
],
"section": null
},
{
"name": "Otaleg! (gelato)",
"address": "Via di San Cosimato 14/A, 00153 Roma",
"order": "About 30 flavours made daily with seasonal ingredients — pistachio is a favourite (Otaleg's own site).",
"price": "€ (prices not published)",
"closed": "Open every day, 12:00–24:00 (own site)",
"booking": "no",
"why": "Given Gambero Rosso's top 'Tre Coni' rating in its 2027 gelato guide; about 4 min walk.",
"sources": [
"https://www.otaleg.com/",
"https://www.scattidigusto.it/migliori-gelaterie-gambero-rosso-2027"
],
"section": null
},
{
"name": "Mercato di San Cosimato (neighbourhood market)",
"address": "Piazza di San Cosimato, 00153 Roma",
"order": "Seasonal fruit and vegetables from Lazio farmers (Velletri, Cori), plus cheese, cured meats and fish stalls — picnic or breakfast supplies (mercatidiroma.com).",
"price": "€",
"closed": "Sunday; open Monday–Saturday 6:00–13:30",
"booking": "no",
"why": "Trastevere's everyday morning market, on the square at the end of your street.",
"sources": [
"https://mercatidiroma.com/mercato-san-cosimato/mercato-san-cosimato",
"https://www.turismoroma.it/en/places/mercato-rionale-trastevere-piazza-san-cosimato"
],
"section": null
},
{
"name": "Romanè (lunch near the Vatican Museums)",
"address": "Via Cipro 106, 00136 Roma",
"order": "Amatriciana, carbonara, saltimbocca alla romana, pollo alla cacciatora, and ricotta-and-sour-cherry tart; offal dishes (fried brains, tripe) for the adventurous. Per the Michelin Guide.",
"price": "€ (Michelin price band)",
"closed": "Open every day, 12:00–00:30 without a break (Michelin)",
"booking": "advised — phone +39 340 784 5281",
"why": "Michelin Bib Gourmand trattoria from Stefano Callegari (the trapizzino man); about 10 min walk from the Vatican Museums entrance, and the non-stop hours make a late lunch easy.",
"sources": [
"https://guide.michelin.com/us/en/lazio/roma/restaurant/romane",
"https://guide.michelin.com/us/en/lazio/roma/restaurants/bib-gourmand"
],
"section": null
},
{
"name": "La Taverna dei Fori Imperiali (lunch near the Colosseum)",
"address": "Via della Madonna dei Monti 9, 00184 Roma",
"order": "Roman pastas — carbonara, gricia, cacio e pepe — then saltimbocca alla romana or baccalà alla romana (restaurant's own menu).",
"price": "€€ — starters €12–16, pasta €14–18, main courses €13–22 (restaurant's website)",
"closed": "Tuesday",
"booking": "advised — online through Quandoo on the restaurant's website, or phone +39 06 679 8643",
"why": "Family-run for over 20 years on a pretty lane in Monti, about 7 min walk from the Colosseum.",
"sources": [
"https://www.latavernadeiforiimperiali.com/",
"https://www.sluurpy.it/roma/ristorante/39036/la-taverna-dei-fori-imperiali"
],
"section": null
}
],
"foods_to_try": [
{
"food": "carciofo alla giudia",
"what": "A whole artichoke deep-fried until its leaves open up crisp like a flower — a Roman-Jewish classic."
},
{
"food": "carciofi alla romana",
"what": "Artichokes gently braised with garlic, parsley and wild mint."
},
{
"food": "coda alla vaccinara",
"what": "Oxtail slow-stewed in tomato with plenty of celery; some cooks add pine nuts, raisins and a little cocoa."
},
{
"food": "trippa alla romana",
"what": "Tripe stewed in tomato sauce, finished with mint and grated pecorino."
},
{
"food": "saltimbocca alla romana",
"what": "Thin slices of veal topped with prosciutto and a sage leaf, cooked in butter and white wine."
},
{
"food": "pizza romana",
"what": "Rome's own round pizza — very thin and crackly, unlike the soft, puffy Naples style."
},
{
"food": "pizza al taglio",
"what": "Pizza baked in big trays and sold by the slice, priced by weight."
},
{
"food": "maritozzo con la panna",
"what": "A soft sweet bun split open and filled with whipped cream — a Roman breakfast treat."
}
]
}
];
