// Houses for sale ≤ €50,000, collected 23 Sep 2026
window.LISTINGS=[
{
"area": "Trasimeno",
"town": "Panicale",
"title": "Terraced house",
"price_eur": 28000,
"size_m2": 85,
"rooms": "2 bed, 1 bath",
"condition": "needs work",
"address": "Colle Calzolaro, Tavernelle, Panicale",
"address_precision": "locality",
"lat": 43.01229,
"lon": 12.13549,
"url": "https://gate-away.com/properties/umbria/perugia/panicale/id/671882",
"source": "gate-away.com",
"note": "three-level terraced house, storage ground floor, to be restored"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Semi-detached house",
"price_eur": 29000,
"size_m2": 116,
"rooms": "1 bed",
"condition": "needs work",
"address": "Loc. Pucciarelli, Via Firenze 11, Castiglione del Lago",
"address_precision": "exact",
"lat": 43.08382,
"lon": 12.04829,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/843237",
"source": "gate-away.com",
"note": "overlooks Lake Trasimeno, needs renovation, energy class G"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Semi-detached farmhouse portion",
"price_eur": 30000,
"size_m2": 340,
"rooms": null,
"condition": "needs work",
"address": "Castiglione del Lago",
"address_precision": "town",
"lat": 43.12813,
"lon": 12.04626,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/754005",
"source": "gate-away.com",
"note": "12 rooms across 3 levels, terracotta floors and fireplaces, to be restored"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Country house (rural annex)",
"price_eur": 40000,
"size_m2": 121,
"rooms": null,
"condition": "needs work",
"address": "approx. 4 km from Castiglione del Lago town centre",
"address_precision": "town",
"lat": 43.12599,
"lon": 12.04218,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/809949",
"source": "gate-away.com",
"note": "annex on 4,300 m2 land, convertible to a home, expansion potential"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Apartment",
"price_eur": 43000,
"size_m2": 75,
"rooms": "1 bed, 1 bath",
"condition": "needs work",
"address": "Sanfatucchio, Castiglione del Lago",
"address_precision": "locality",
"lat": 43.07803,
"lon": 12.05213,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/744306",
"source": "gate-away.com",
"note": "ground-floor unit in small 4-unit building, private garage, attic room"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Semi-detached house",
"price_eur": 45000,
"size_m2": 110,
"rooms": "2 bed, 2 bath",
"condition": "needs work",
"address": "Casamaggiore, Castiglione del Lago",
"address_precision": "locality",
"lat": 43.10096139504176,
"lon": 11.969506523193342,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/819602",
"source": "gate-away.com",
"note": "structurally sound, needs interior updates (fixtures/systems/flooring), 3000 m2 olive grove"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Semi-detached house",
"price_eur": 45000,
"size_m2": 125,
"rooms": "2 bed, 2 bath",
"condition": "habitable",
"address": "Loc. Carraia, Castiglione del Lago",
"address_precision": "locality",
"lat": 43.08141,
"lon": 12.0729,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/815344",
"source": "gate-away.com",
"note": "3 levels, rustic ground floor, mansard bedroom with terrace, shared courtyard"
},
{
"area": "Trasimeno",
"town": "Castiglione del Lago",
"title": "Semi-detached house",
"price_eur": 48000,
"size_m2": 110,
"rooms": "2 bed, 1 bath",
"condition": "habitable",
"address": "Poggetto, San Fatucchio, Castiglione del Lago",
"address_precision": "locality",
"lat": 43.0779,
"lon": 12.052,
"url": "https://gate-away.com/properties/umbria/perugia/castiglione-del-lago/id/829811",
"source": "gate-away.com",
"note": "recently inhabited, all utilities, 100 m2 garden plot, 3 levels"
},
{
"area": "Trasimeno",
"town": "Panicale",
"title": "Terraced house",
"price_eur": 50000,
"size_m2": 90,
"rooms": "2 bed, 1 bath",
"condition": "needs work",
"address": "Colle Calzolaro, Tavernelle, Panicale",
"address_precision": "locality",
"lat": 43.01225,
"lon": 12.13545,
"url": "https://gate-away.com/properties/umbria/perugia/panicale/id/671883",
"source": "gate-away.com",
"note": "three-level terraced house, to be restored, ~12 km from Citta della Pieve"
},
{
"area": "Lucca",
"town": "Fivizzano",
"title": "Historic stone house",
"price_eur": 11500,
"size_m2": 80,
"rooms": "2 bed, 1 bath",
"condition": "needs work",
"address": "Vezzanello, Fivizzano",
"address_precision": "locality",
"lat": 44.1739683,
"lon": 10.0975356,
"url": "https://gate-away.com/properties/tuscany/massa-carrara/fivizzano/id/534978",
"source": "gate-away.com",
"note": "mountain property, renovation grants available, garden/terrace/cellar"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "House",
"price_eur": 15000,
"size_m2": 35,
"rooms": "1 bed, 1 bath",
"condition": "needs work",
"address": "San Cassiano area, Bagni di Lucca",
"address_precision": "locality",
"lat": 44.0424646,
"lon": 10.6302819,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/835876",
"source": "gate-away.com",
"note": "stone restoration project, hillside, panoramic valley views"
},
{
"area": "Lucca",
"town": "Borgo a Mozzano",
"title": "Mill (stone shed)",
"price_eur": 23000,
"size_m2": 32,
"rooms": "1 bed",
"condition": "needs work",
"address": "Borgo a Mozzano, near historic fortress ruins",
"address_precision": "town",
"lat": 43.9957,
"lon": 10.5464,
"url": "https://gate-away.com/properties/tuscany/lucca/borgo-a-mozzano/id/705664",
"source": "gate-away.com",
"note": "small stone shed, two floors, quiet village ~25 km from Lucca city"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "Semi-detached house portion",
"price_eur": 25000,
"size_m2": 45,
"rooms": "2 bed, 1 bath",
"condition": "needs work",
"address": "Via del Condotto, 30, Montefegatesi, Bagni di Lucca",
"address_precision": "exact",
"lat": 44.062208,
"lon": 10.5939669,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/738229",
"source": "gate-away.com",
"note": "medieval mountain village at 850m elevation, cellar, fireplace, near ski facilities"
},
{
"area": "Lucca",
"town": "Fivizzano",
"title": "Farmhouse",
"price_eur": 29000,
"size_m2": 100,
"rooms": "2 bed, 2 bath",
"condition": "needs work",
"address": "Fivizzano (medieval village, unnamed hamlet)",
"address_precision": "town",
"lat": 44.23835,
"lon": 10.12599,
"url": "https://gate-away.com/properties/tuscany/massa-carrara/fivizzano/id/370892",
"source": "gate-away.com",
"note": "rustic stone farmhouse, valley and Alps views, garden and cellar, water/electricity connected"
},
{
"area": "Lucca",
"town": "Gallicano",
"title": "Farmhouse annex",
"price_eur": 29000,
"size_m2": 40,
"rooms": null,
"condition": "needs work",
"address": "near Lago Tre Canali, Gallicano",
"address_precision": "locality",
"lat": 44.064465,
"lon": 10.4413684,
"url": "https://gate-away.com/properties/tuscany/lucca/gallicano/id/811862",
"source": "gate-away.com",
"note": "agricultural annex on 3,500 m2 flat lakefront land, accessed via dirt road"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "House",
"price_eur": 30000,
"size_m2": 90,
"rooms": "3 bed, 2 bath",
"condition": "needs work",
"address": "Benabbio, Bagni di Lucca",
"address_precision": "locality",
"lat": 43.9985,
"lon": 10.6028,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/777713",
"source": "gate-away.com",
"note": "3-floor stone village house, vaulted cellars, private terrace, hilltop setting"
},
{
"area": "Lucca",
"town": "Fivizzano",
"title": "Village house",
"price_eur": 30000,
"size_m2": 62,
"rooms": "2 bed",
"condition": "habitable",
"address": "Fivizzano (historic hamlet, unnamed)",
"address_precision": "town",
"lat": 44.23835,
"lon": 10.12599,
"url": "https://gate-away.com/properties/tuscany/massa-carrara/fivizzano/id/834936",
"source": "gate-away.com",
"note": "restored, panoramic balcony, pellet stove heating, fully furnished"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "Apartment",
"price_eur": 32000,
"size_m2": 75,
"rooms": "2 bed",
"condition": "needs work",
"address": "Bagni di Lucca",
"address_precision": "town",
"lat": 44.007539,
"lon": 10.579274,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/679221",
"source": "gate-away.com",
"note": "partially restored, two-level, traditional palazzo, riverside views"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "Country house (farmhouse)",
"price_eur": 35000,
"size_m2": 50,
"rooms": "1 bed, 1 bath",
"condition": "needs work",
"address": "Montefegatesi, Bagni di Lucca",
"address_precision": "locality",
"lat": 44.0395599,
"lon": 10.6119252,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/738200",
"source": "gate-away.com",
"note": "hillside farmhouse on ~1 hectare, near ski resort (Abetone), needs renovation"
},
{
"area": "Lucca",
"town": "Bagni di Lucca",
"title": "Semi-detached house",
"price_eur": 35000,
"size_m2": 106,
"rooms": "2 bed, 1 bath",
"condition": "habitable",
"address": "Lugliano, Bagni di Lucca",
"address_precision": "locality",
"lat": 43.998242,
"lon": 10.574147,
"url": "https://gate-away.com/properties/tuscany/lucca/bagni-di-lucca/id/821283",
"source": "gate-away.com",
"note": "fireplace, two bright bedrooms upstairs, cellar storage, 71 m2 usable + 33 m2 cellar"
},
{
"area": "Lucca",
"town": "Coreglia Antelminelli",
"title": "Loft (village property)",
"price_eur": 35000,
"size_m2": 110,
"rooms": "6 bed",
"condition": "needs work",
"address": "Coreglia Antelminelli",
"address_precision": "town",
"lat": 44.0636526,
"lon": 10.525509,
"url": "https://gate-away.com/properties/tuscany/lucca/coreglia-antelminelli/id/798914",
"source": "gate-away.com",
"note": "original beams and stone walls, planning permission presented, 3 levels"
},
{
"area": "Lucca",
"town": "Fivizzano",
"title": "Apartment",
"price_eur": 35000,
"size_m2": 55,
"rooms": "1 bed, 1 bath",
"condition": "habitable",
"address": "Fivizzano (unnamed hamlet)",
"address_precision": "town",
"lat": 44.23835,
"lon": 10.12599,
"url": "https://gate-away.com/properties/tuscany/massa-carrara/fivizzano/id/834941",
"source": "gate-away.com",
"note": "recently renovated first-floor unit, shared garden/terrace/parking, near ski resorts"
},
{
"area": "Lucca",
"town": "Borgo a Mozzano",
"title": "Detached townhouse",
"price_eur": 35000,
"size_m2": 90,
"rooms": "2 bed, 1 bath",
"condition": "needs work",
"address": "San Romano area, Borgo a Mozzano",
"address_precision": "locality",
"lat": 44.017116,
"lon": 10.496922,
"url": "https://gate-away.com/properties/tuscany/lucca/borgo-a-mozzano/id/770070",
"source": "gate-away.com",
"note": "multi-level, cellars, courtyard parking, quiet historic setting"
},
{
"area": "Lucca",
"town": "Barga",
"title": "Semi-detached house",
"price_eur": 45000,
"size_m2": 90,
"rooms": "3 bed, 3 bath",
"condition": "habitable",
"address": "Fornaci di Barga, Barga",
"address_precision": "locality",
"lat": 44.0449068,
"lon": 10.4802317,
"url": "https://gate-away.com/properties/tuscany/lucca/barga/id/830702",
"source": "gate-away.com",
"note": "stone house, 3 levels, immediately habitable, single-glazed windows, no heating, walk to shops/station"
},
{
"area": "Pescara",
"town": "Celenza sul Trigno",
"title": "House to renovate",
"price_eur": 11000,
"size_m2": 70,
"rooms": 3,
"condition": "needs work",
"address": "Celenza sul Trigno, Chieti",
"address_precision": "town",
"lat": 41.8721703,
"lon": 14.5790332,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/celenza-sul-trigno/id/724964",
"source": "gate-away.com",
"note": "Stone house in historic centre, roof needs work but beams reusable, has terrace and fireplace"
},
{
"area": "Pescara",
"town": "Penne",
"title": "Ruin with agricultural land",
"price_eur": 15000,
"size_m2": 50,
"rooms": null,
"condition": "needs work",
"address": "C.da Colle Stella, Penne, Pescara",
"address_precision": "locality",
"lat": 42.45541,
"lon": 13.9677,
"url": "https://www.gate-away.com/properties/abruzzo/pescara/penne/id/822775",
"source": "gate-away.com",
"note": "Ruin to fully renovate, 2,140 m2 of agricultural land, south-east exposure over a valley"
},
{
"area": "Pescara",
"town": "Carunchio",
"title": "Stone house to restore",
"price_eur": 18000,
"size_m2": 150,
"rooms": 3,
"condition": "needs work",
"address": "Carunchio, Chieti",
"address_precision": "town",
"lat": 41.92,
"lon": 14.52,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/carunchio/id/578776",
"source": "gate-away.com",
"note": "Hilltop stone house to be restored, ground floor cellar and fireplace, virtual tour available"
},
{
"area": "Pescara",
"town": "Celenza sul Trigno",
"title": "Village house, restored",
"price_eur": 19000,
"size_m2": 65,
"rooms": 1,
"condition": "habitable",
"address": "Celenza sul Trigno, Chieti",
"address_precision": "town",
"lat": 41.8721703,
"lon": 14.5790332,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/celenza-sul-trigno/id/615897",
"source": "gate-away.com",
"note": "Fully restored, roof/structure in excellent condition, panoramic mountain views, cellar and fireplace"
},
{
"area": "Pescara",
"town": "Tufillo",
"title": "Restored stone townhouse",
"price_eur": 22000,
"size_m2": 70,
"rooms": 2,
"condition": "habitable",
"address": "Tufillo, Chieti",
"address_precision": "town",
"lat": 41.9164633,
"lon": 14.6260061,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/tufillo/id/808822",
"source": "gate-away.com",
"note": "Completely restored, sold furnished, vaulted ceilings, own 60 m2 garden and 17 m2 courtyard"
},
{
"area": "Pescara",
"town": "Celenza sul Trigno",
"title": "Townhouse, independent unit",
"price_eur": 22000,
"size_m2": 63,
"rooms": 3,
"condition": "habitable",
"address": "Celenza sul Trigno, Chieti",
"address_precision": "town",
"lat": 41.8721703,
"lon": 14.5790332,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/celenza-sul-trigno/id/757494",
"source": "gate-away.com",
"note": "Completely restored, central heating, ready to live in, roof terrace with village views"
},
{
"area": "Pescara",
"town": "Castelguidone",
"title": "Three-storey stone house",
"price_eur": 25000,
"size_m2": 90,
"rooms": 3,
"condition": "habitable",
"address": "Castelguidone, Chieti",
"address_precision": "town",
"lat": 41.82,
"lon": 14.52,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/castelguidone/id/769914",
"source": "gate-away.com",
"note": "Light internal renovation/maintenance needed, roof fully restored 2022, vaulted stone cellar"
},
{
"area": "Pescara",
"town": "Tufillo",
"title": "Town house, partially restored",
"price_eur": 25000,
"size_m2": 100,
"rooms": 3,
"condition": "needs work",
"address": "Tufillo, Chieti",
"address_precision": "town",
"lat": 41.9164633,
"lon": 14.6260061,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/tufillo/id/751730",
"source": "gate-away.com",
"note": "Utilities need reconnecting, walking distance to centre, views of Majella and Matese mountains"
},
{
"area": "Pescara",
"town": "Tufillo",
"title": "House, unoccupied 20+ years",
"price_eur": 25000,
"size_m2": 100,
"rooms": 2,
"condition": "needs work",
"address": "Tufillo, Chieti",
"address_precision": "town",
"lat": 41.9164633,
"lon": 14.6260061,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/tufillo/id/751734",
"source": "gate-away.com",
"note": "No bathroom currently, needs full renovation, garden, terrace and three cellars"
},
{
"area": "Pescara",
"town": "Atessa",
"title": "Farmhouse to restore",
"price_eur": 35000,
"size_m2": 92,
"rooms": 2,
"condition": "needs work",
"address": "Atessa, Chieti",
"address_precision": "town",
"lat": 42.06671,
"lon": 14.44606,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/atessa/id/759805",
"source": "gate-away.com",
"note": "Semi-detached, sea view, 1,155 m2 land, option to buy adjacent habitable farmhouse"
},
{
"area": "Pescara",
"town": "Carunchio",
"title": "Town house, partially restored",
"price_eur": 34000,
"size_m2": 135,
"rooms": 5,
"condition": "needs work",
"address": "Carunchio, Chieti",
"address_precision": "town",
"lat": 41.916634,
"lon": 14.526722,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/carunchio/id/724966",
"source": "gate-away.com",
"note": "Huge town house across three storeys, spacious balcony, one room needs ceiling work"
},
{
"area": "Pescara",
"town": "Penne",
"title": "Early-1900s townhouse, restored",
"price_eur": 34000,
"size_m2": 145,
"rooms": 3,
"condition": "habitable",
"address": "Penne, Pescara",
"address_precision": "town",
"lat": 42.4573,
"lon": 13.9298,
"url": "https://www.gate-away.com/properties/abruzzo/pescara/penne/id/850923",
"source": "gate-away.com",
"note": "Original barrel vaults and period flooring, small terrace, 35 m2 cellar, B&B potential"
},
{
"area": "Pescara",
"town": "Atessa",
"title": "Renovated apartment, Via San Spirito",
"price_eur": 47000,
"size_m2": 100,
"rooms": 3,
"condition": "habitable",
"address": "Via San Spirito 16, Atessa, Chieti",
"address_precision": "exact",
"lat": 42.069157,
"lon": 14.449098,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/atessa/id/844626",
"source": "gate-away.com",
"note": "Recently renovated with quality materials, valley-view terrace, shared garden, private parking"
},
{
"area": "Pescara",
"town": "Citta Sant'Angelo",
"title": "Former olive mill to restore",
"price_eur": 48000,
"size_m2": 145,
"rooms": 6,
"condition": "needs work",
"address": "Citta Sant'Angelo, Pescara",
"address_precision": "town",
"lat": 42.515513,
"lon": 14.072402,
"url": "https://www.gate-away.com/properties/abruzzo/pescara/citta-sant-angelo/id/838034",
"source": "gate-away.com",
"note": "Former olive mill with vaulted ceilings and residual machinery, needs full renovation"
},
{
"area": "Pescara",
"town": "Guardiagrele",
"title": "Restored townhouse, Bocca di Valle",
"price_eur": 50000,
"size_m2": 166,
"rooms": 3,
"condition": "habitable",
"address": "Bocca di Valle, Guardiagrele, Chieti",
"address_precision": "locality",
"lat": 42.1795139,
"lon": 14.179728,
"url": "https://www.gate-away.com/properties/abruzzo/chieti/guardiagrele/id/724324",
"source": "gate-away.com",
"note": "Fully restored over four levels, panoramic terraces, shared 580 m2 courtyard, near Maiella park"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Via Boccardelli",
"price_eur": 15000,
"size_m2": 40,
"rooms": 1,
"condition": "needs work",
"address": "Via Boccardelli, Segni",
"address_precision": "street",
"lat": 41.6913634,
"lon": 13.0267786,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/809839",
"source": "gate-away.com",
"note": "Ground floor unit in historic centre with cellar access, independent entrance"
},
{
"area": "Rome",
"town": "Artena",
"title": "Studio apartment, Via Maggiore",
"price_eur": 15500,
"size_m2": 40,
"rooms": 1,
"condition": "needs work",
"address": "Via Maggiore, Artena",
"address_precision": "street",
"lat": 41.737908,
"lon": 12.915527,
"url": "https://www.gate-away.com/properties/lazio/rome/artena/id/801359",
"source": "gate-away.com",
"note": "Europe's largest car-free historic centre, direct access to main street, balcony"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Via Felici",
"price_eur": 18000,
"size_m2": 41,
"rooms": 1,
"condition": "needs work",
"address": "Via Felici, Segni",
"address_precision": "street",
"lat": 41.6948,
"lon": 13.0256,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799288",
"source": "gate-away.com",
"note": "Triple exposure south-east-west, near three public parking lots, windows already renewed"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Via Rossi",
"price_eur": 17000,
"size_m2": 45,
"rooms": 2,
"condition": "needs work",
"address": "Via Rossi, Segni",
"address_precision": "street",
"lat": 41.69442833,
"lon": 13.023755107,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799319",
"source": "gate-away.com",
"note": "2nd floor, no lift, 1970s systems and frames, panoramic view above the cathedral, cellar and attic"
},
{
"area": "Rome",
"town": "Segni",
"title": "Rustic apartment, Via Caratelli",
"price_eur": 17000,
"size_m2": 42,
"rooms": 1,
"condition": "needs work",
"address": "Via Caratelli, Segni",
"address_precision": "street",
"lat": 41.69,
"lon": 13.02,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799286",
"source": "gate-away.com",
"note": "Two-level rustic style, mezzanine sleeping area, stone/wood finishes, independent entrance"
},
{
"area": "Rome",
"town": "Segni",
"title": "Palace apartment, Via Tomassi",
"price_eur": 22000,
"size_m2": 68,
"rooms": 1,
"condition": "needs work",
"address": "Via Tomassi, Segni",
"address_precision": "street",
"lat": 41.6927,
"lon": 13.0249,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799298",
"source": "gate-away.com",
"note": "South-facing, roof already renovated, cellar, fireplace, balcony, roof access, utilities connected"
},
{
"area": "Rome",
"town": "Artena",
"title": "Apartment, Via Cavour area",
"price_eur": 24000,
"size_m2": 44,
"rooms": 1,
"condition": "needs work",
"address": "Via Cavour, Artena",
"address_precision": "street",
"lat": 41.739,
"lon": 12.914,
"url": "https://www.gate-away.com/properties/lazio/rome/artena/id/842451",
"source": "gate-away.com",
"note": "Ground floor, independent entrance, private cellar, historic centre"
},
{
"area": "Rome",
"town": "Segni",
"title": "Two connected apartments, Piazza Santa Lucia",
"price_eur": 29000,
"size_m2": 100,
"rooms": 3,
"condition": "needs work",
"address": "Piazza Santa Lucia, Segni",
"address_precision": "street",
"lat": 41.6938,
"lon": 13.0258,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799294",
"source": "gate-away.com",
"note": "Third floor, panoramic valley views, double exposure, near public parking, both units need work"
},
{
"area": "Rome",
"town": "Artena",
"title": "Villa, historic centre",
"price_eur": 32000,
"size_m2": 60,
"rooms": 2,
"condition": "habitable",
"address": "Artena, Rome",
"address_precision": "town",
"lat": 41.739029,
"lon": 12.90634,
"url": "https://www.gate-away.com/properties/lazio/rome/artena/id/835831",
"source": "gate-away.com",
"note": "Completely restored, two levels, panoramic views from upper floor, parking 100 m away"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Piazza Persichilli",
"price_eur": 25000,
"size_m2": 67,
"rooms": 1,
"condition": "needs work",
"address": "Piazza Persichilli, Segni",
"address_precision": "street",
"lat": 41.6943527,
"lon": 13.0251103,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/810853",
"source": "gate-away.com",
"note": "Systems need renewal, new double-glazed windows, exclusive courtyard, terrace and cellar"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Via Dante",
"price_eur": 25000,
"size_m2": 64,
"rooms": 4,
"condition": "needs work",
"address": "Via Dante, Segni",
"address_precision": "street",
"lat": 41.691805,
"lon": 13.023632,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/812082",
"source": "gate-away.com",
"note": "1970s systems and single-glazed aluminium frames, two bathrooms, two kitchens, 10 m2 cellar"
},
{
"area": "Rome",
"town": "Segni",
"title": "Building, Via Giacomo Puccini",
"price_eur": 25000,
"size_m2": 65,
"rooms": 2,
"condition": "needs work",
"address": "Via Giacomo Puccini, Segni",
"address_precision": "street",
"lat": 41.6917578,
"lon": 13.026081,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/814555",
"source": "gate-away.com",
"note": "Three-level independent building, 1970s systems, updated roof, basement fireplace"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Vicolo Mauri",
"price_eur": 35000,
"size_m2": 50,
"rooms": 2,
"condition": "needs work",
"address": "Vicolo Mauri, Segni",
"address_precision": "street",
"lat": 41.694347,
"lon": 13.0254418,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/799280",
"source": "gate-away.com",
"note": "Three levels, independent access, fireplace in living room, near public parking and shops"
},
{
"area": "Rome",
"town": "Segni",
"title": "Apartment, Via Ciminelli",
"price_eur": 35000,
"size_m2": 75,
"rooms": 2,
"condition": "habitable",
"address": "Via Ciminelli, Segni",
"address_precision": "street",
"lat": 41.6938148,
"lon": 13.0246471,
"url": "https://www.gate-away.com/properties/lazio/rome/segni/id/809843",
"source": "gate-away.com",
"note": "Good condition, double exposure, two cellars (one with bathroom), fireplace and attic"
},
{
"area": "Rome",
"town": "Artena",
"title": "Restored townhouse",
"price_eur": 45000,
"size_m2": 65,
"rooms": 2,
"condition": "habitable",
"address": "Artena, Rome",
"address_precision": "town",
"lat": 41.7419154,
"lon": 12.9121745,
"url": "https://www.gate-away.com/properties/lazio/rome/artena/id/827362",
"source": "gate-away.com",
"note": "Completely restored, eat-in kitchen, ensuite double bedroom, private 40 m2 courtyard"
},
{
"area": "Lecce",
"town": "Casarano",
"title": "Detached house",
"price_eur": 35000,
"size_m2": 90,
"rooms": 1,
"condition": "needs work (partially restored, needs customization)",
"address": "Via Pellegrino, Casarano",
"address_precision": "street",
"lat": 40.0099086,
"lon": 18.1632848,
"url": "https://www.gate-away.com/properties/puglia/lecce/casarano/id/804034",
"source": "gate-away.com",
"note": "raised ground floor, private terrace, star-vaulted rooms, basement storage"
},
{
"area": "Lecce",
"town": "Casarano",
"title": "Semi-detached house (multi-unit, historic center)",
"price_eur": 38000,
"size_m2": 115,
"rooms": 7,
"condition": "needs work (completely in need of renovation)",
"address": "Via Ugo Bassi, Casarano",
"address_precision": "street",
"lat": 40.0091387,
"lon": 18.1628097,
"url": "https://www.gate-away.com/properties/puglia/lecce/casarano/id/825666",
"source": "gate-away.com",
"note": "traditional star-vault ceilings, roof terrace, courtyard; suited to B&B conversion"
},
{
"area": "Lecce",
"town": "Galatina",
"title": "Detached house (corner unit)",
"price_eur": 39000,
"size_m2": 123,
"rooms": 2,
"condition": "needs work (requires complete renovation, including attics)",
"address": "Via Bologna, Galatina",
"address_precision": "street",
"lat": 40.1790428,
"lon": 18.1808943,
"url": "https://www.gate-away.com/properties/puglia/lecce/galatina/id/832544",
"source": "gate-away.com",
"note": "approved project for new two-storey build; train station 1.4 km"
},
{
"area": "Lecce",
"town": "Ugento",
"title": "Apartment (historic center)",
"price_eur": 41500,
"size_m2": 30,
"rooms": 1,
"condition": "habitable (completely restored)",
"address": "Ugento",
"address_precision": "town",
"lat": 39.9284717,
"lon": 18.1622792,
"url": "https://www.gate-away.com/properties/puglia/lecce/ugento/id/788119",
"source": "gate-away.com",
"note": "exposed stone walls, 6.2 km from coast, exact street not disclosed by advertiser"
},
{
"area": "Lecce",
"town": "Nardò",
"title": "Apartment (historic center, first floor)",
"price_eur": 48000,
"size_m2": 75,
"rooms": 1,
"condition": "needs work (to be restored)",
"address": "Nardò",
"address_precision": "town",
"lat": 40.1762608,
"lon": 18.0306371,
"url": "https://www.gate-away.com/properties/puglia/lecce/nardo/id/836659",
"source": "gate-away.com",
"note": "star-vaulted ceilings, private rooftop terrace, steps from historic center, exact street not disclosed"
},
{
"area": "Lecce",
"town": "Casarano",
"title": "Apartment, second floor",
"price_eur": 50000,
"size_m2": 90,
"rooms": 2,
"condition": "habitable (partially restored, furnished, move-in ready)",
"address": "Via Grandi, Casarano",
"address_precision": "street",
"lat": 40.0037,
"lon": 18.1592,
"url": "https://www.gate-away.com/properties/puglia/lecce/casarano/id/796826",
"source": "gate-away.com",
"note": "balconies off bedroom and kitchen, near train station and bus stop"
},
{
"area": "Salerno",
"town": "Eboli",
"title": "Apartment (judicial auction)",
"price_eur": 16420,
"size_m2": 62,
"rooms": null,
"condition": null,
"address": "Via Vicolo IV Rua 13, Eboli",
"address_precision": "exact",
"lat": 40.6175146,
"lon": 15.0569438,
"url": "https://www.trovacasa.it/annunci/sa-tc-69048-73115449",
"source": "trovacasa.it",
"note": "judicial auction listing; fireplace, independent entrance; coordinates are town-centre fallback since street could not be geocoded precisely"
},
{
"area": "Salerno",
"town": "Eboli",
"title": "Apartment (judicial auction)",
"price_eur": 20390,
"size_m2": 48,
"rooms": null,
"condition": null,
"address": "Via Francesco Crispi 14, Eboli",
"address_precision": "exact",
"lat": 40.4882664,
"lon": 14.9468291,
"url": "https://www.trovacasa.it/annunci/sa-tc-69048-73115073",
"source": "trovacasa.it",
"note": "judicial auction listing; private garden mentioned"
},
{
"area": "Salerno",
"town": "Altavilla Silentina",
"title": "Apartment (3 rooms)",
"price_eur": 22000,
"size_m2": 99,
"rooms": 2,
"condition": "needs work (da ristrutturare)",
"address": "Vicolo Caruso 17, Altavilla Silentina",
"address_precision": "exact",
"lat": 40.5302405,
"lon": 15.1310307,
"url": "https://www.bancadellecase.it/appartamento-trilocale-in-vendita-a-altavilla-silentina_5045757",
"source": "bancadellecase.it",
"note": "ground floor, three exposed sides, cellar, fireplace; coordinates are town-centre fallback (street not geocoded); on Battipaglia-Potenza rail line"
},
{
"area": "Salerno",
"town": "Sarno",
"title": "Studio apartment",
"price_eur": 23000,
"size_m2": 30,
"rooms": null,
"condition": "needs work (da ristrutturare)",
"address": "Via Mazzini 22, Sarno",
"address_precision": "exact",
"lat": 40.8135095,
"lon": 14.6214529,
"url": "https://www.bancadellecase.it/appartamento-monolocale-in-vendita-a-sarno_5058611",
"source": "bancadellecase.it",
"note": "balcony, loggia, storage room; about 300 m from Sarno train station"
},
{
"area": "Salerno",
"town": "Eboli",
"title": "Villa (judicial auction)",
"price_eur": 34420,
"size_m2": 113,
"rooms": null,
"condition": null,
"address": "Via Giulia Rossa, Contrada Cioffi, Eboli",
"address_precision": "locality",
"lat": 40.5486516,
"lon": 14.9887994,
"url": "https://www.trovacasa.it/annunci/sa-tc-69048-73117125",
"source": "trovacasa.it",
"note": "judicial auction listing; agricultural zone, private garden mentioned"
},
{
"area": "Salerno",
"town": "Sarno",
"title": "Two-level terraced house",
"price_eur": 45000,
"size_m2": 103,
"rooms": 2,
"condition": "needs work (uninhabited, da ristrutturare)",
"address": "Via San Valentino 120, Sarno",
"address_precision": "exact",
"lat": 40.8040316,
"lon": 14.6110086,
"url": "https://www.bancadellecase.it/casa-bilocale-in-vendita-a-sarno_5055880",
"source": "bancadellecase.it",
"note": "ground floor entrance/kitchen/bath, upper floor 2 bedrooms, external courtyard, separate garage"
},
{
"area": "Salerno",
"town": "Eboli",
"title": "Villa (judicial auction)",
"price_eur": 45440,
"size_m2": 105,
"rooms": null,
"condition": null,
"address": "Via Mirabella 55, Eboli",
"address_precision": "exact",
"lat": 40.6258795,
"lon": 15.0766415,
"url": "https://www.trovacasa.it/annunci/sa-tc-69048-73119840",
"source": "trovacasa.it",
"note": "judicial auction listing"
},
{
"area": "Salerno",
"town": "Battipaglia",
"title": "Apartment, ground floor",
"price_eur": 48590,
"size_m2": 72,
"rooms": null,
"condition": "habitable (furnished, good condition)",
"address": "Via Pisano 12, Battipaglia",
"address_precision": "exact",
"lat": 40.6172598,
"lon": 14.9615604,
"url": "https://www.trovacasa.it/annunci/sa-tc-69048-73122724",
"source": "trovacasa.it",
"note": "autonomous heating, ground floor unit, normal sale (not auction)"
}
];
