// More Wikimedia Commons photos (credits shown on the page)
Object.assign(window.PHOTOS, {
"Rocca_del_Leone":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/Rocca_del_Leone_-_Castiglione_del_Lago_45.jpg/960px-Rocca_del_Leone_-_Castiglione_del_Lago_45.jpg","p":"https://commons.wikimedia.org/wiki/File:Rocca_del_Leone_-_Castiglione_del_Lago_45.jpg","b":"Diego Baglieri","l":"CC BY-SA 4.0"},
"Palazzo_della_Corgna":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Castiglione_del_Lago_Palazzo_Ducale_dei_Della_Corgna.jpg/960px-Castiglione_del_Lago_Palazzo_Ducale_dei_Della_Corgna.jpg","p":"https://commons.wikimedia.org/wiki/File:Castiglione_del_Lago_Palazzo_Ducale_dei_Della_Corgna.jpg","b":"Maurizio Zanetti","l":"CC BY 2.0"},
"Castiglione_lakefront":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Lago_Trasimeno%2C_veduta_dalla_fortezza_di_Castiglione_del_Lago%2C_Perugia.jpg/960px-Lago_Trasimeno%2C_veduta_dalla_fortezza_di_Castiglione_del_Lago%2C_Perugia.jpg","p":"https://commons.wikimedia.org/wiki/File:Lago_Trasimeno,_veduta_dalla_fortezza_di_Castiglione_del_Lago,_Perugia.jpg","b":"MichEla Co","l":"CC BY-SA 4.0"},
"Cortona_Piazza":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Cortona%2C_Piazza_della_Repubblica_e_Palazzo_comunale.jpg/960px-Cortona%2C_Piazza_della_Repubblica_e_Palazzo_comunale.jpg","p":"https://commons.wikimedia.org/wiki/File:Cortona,_Piazza_della_Repubblica_e_Palazzo_comunale.jpg","b":"Repuli","l":"CC BY-SA 4.0"},
"Assisi_town":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Assisi-Ansicht.jpg/960px-Assisi-Ansicht.jpg","p":"https://commons.wikimedia.org/wiki/File:Assisi-Ansicht.jpg","b":"Adrian Michael","l":"CC BY-SA 3.0"},
"San_Michele_Lucca":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Lucca_San_Michele_in_Foro_01.jpg/960px-Lucca_San_Michele_in_Foro_01.jpg","p":"https://commons.wikimedia.org/wiki/File:Lucca_San_Michele_in_Foro_01.jpg","b":"Spike","l":"CC BY-SA 4.0"},
"Lucca_Cathedral":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Lucca_Cattedrale_di_San_Martino_Esterno_Facciata_2.jpg/960px-Lucca_Cattedrale_di_San_Martino_Esterno_Facciata_2.jpg","p":"https://commons.wikimedia.org/wiki/File:Lucca_Cattedrale_di_San_Martino_Esterno_Facciata_2.jpg","b":"Zairon","l":"CC BY 4.0"},
"Pisa_Miracoli":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Pisa_piazza_miracoli2.jpg/960px-Pisa_piazza_miracoli2.jpg","p":"https://commons.wikimedia.org/wiki/File:Pisa_piazza_miracoli2.jpg","b":"Alessio Facchin","l":"CC BY-SA 3.0"},
"Palazzo_Vecchio":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Firenze_-_Florence_-_Piazza_della_Signoria_-_View_ESE_on_Palazzo_Vecchio_II.jpg/960px-Firenze_-_Florence_-_Piazza_della_Signoria_-_View_ESE_on_Palazzo_Vecchio_II.jpg","p":"https://commons.wikimedia.org/wiki/File:Firenze_-_Florence_-_Piazza_della_Signoria_-_View_ESE_on_Palazzo_Vecchio_II.jpg","b":"Txllxt TxllxT","l":"CC BY-SA 4.0"},
"Pescara_beach":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Pescara_Lungomare_e_Pineta_Nord0001.JPG/960px-Pescara_Lungomare_e_Pineta_Nord0001.JPG","p":"https://commons.wikimedia.org/wiki/File:Pescara_Lungomare_e_Pineta_Nord0001.JPG","b":"Freegiampi","l":"CC BY-SA 2.5"},
"Lecce_Amphitheatre":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Lecce_amphi_romano_pano.jpg/960px-Lecce_amphi_romano_pano.jpg","p":"https://commons.wikimedia.org/wiki/File:Lecce_amphi_romano_pano.jpg","b":"Velvet","l":"CC BY-SA 3.0"},
"Lecce_Duomo":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Piazza_Duomo_%28Lecce%29_01.jpg/960px-Piazza_Duomo_%28Lecce%29_01.jpg","p":"https://commons.wikimedia.org/wiki/File:Piazza_Duomo_(Lecce)_01.jpg","b":"Bernard Gagnon","l":"CC0"},
"Gallipoli_beach":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Gallipoli_-_Spiaggia_della_Purit%C3%A0.jpg/960px-Gallipoli_-_Spiaggia_della_Purit%C3%A0.jpg","p":"https://commons.wikimedia.org/wiki/File:Gallipoli_-_Spiaggia_della_Purit%C3%A0.jpg","b":"Benjamin Smith","l":"CC BY-SA 4.0"},
"Otranto_Castle":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/010_Castello_Aragonese_%28Otranto%29%2C_basti%C3%B3_pentagonal.jpg/960px-010_Castello_Aragonese_%28Otranto%29%2C_basti%C3%B3_pentagonal.jpg","p":"https://commons.wikimedia.org/wiki/File:010_Castello_Aragonese_(Otranto),_basti%C3%B3_pentagonal.jpg","b":"Enric","l":"CC BY-SA 4.0"},
"Pompeii_Forum":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Forum_%28Pompeii%29_and_the_Vesuvio.jpg/960px-Forum_%28Pompeii%29_and_the_Vesuvio.jpg","p":"https://commons.wikimedia.org/wiki/File:Forum_(Pompeii)_and_the_Vesuvio.jpg","b":"Commonists","l":"CC BY-SA 4.0"},
"Paestum_Neptune":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Capaccio_Paestum_-_Tempio_di_Nettuno.jpg/960px-Capaccio_Paestum_-_Tempio_di_Nettuno.jpg","p":"https://commons.wikimedia.org/wiki/File:Capaccio_Paestum_-_Tempio_di_Nettuno.jpg","b":"AlessioAg89","l":"CC BY-SA 4.0"},
"Salerno_Lungomare":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Lungomare_Trieste_e_centro_storico_di_Salerno.jpg/960px-Lungomare_Trieste_e_centro_storico_di_Salerno.jpg","p":"https://commons.wikimedia.org/wiki/File:Lungomare_Trieste_e_centro_storico_di_Salerno.jpg","b":"SOLOXSALERNO (Italian Wikipedia)","l":"Public domain"},
"Vatican_Stairs":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Vatican_Museums_Spiral_Staircase_2012.jpg/960px-Vatican_Museums_Spiral_Staircase_2012.jpg","p":"https://commons.wikimedia.org/wiki/File:Vatican_Museums_Spiral_Staircase_2012.jpg","b":"Colin","l":"CC BY-SA 3.0"},
"Villa_Borghese":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Laghetto_and_Tempio_di_Esculapio_in_Villa_Borghese_04.jpg/960px-Laghetto_and_Tempio_di_Esculapio_in_Villa_Borghese_04.jpg","p":"https://commons.wikimedia.org/wiki/File:Laghetto_and_Tempio_di_Esculapio_in_Villa_Borghese_04.jpg","b":"Krzysztof Golik","l":"CC BY-SA 4.0"},
"Colosseum_inside":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Colosseum_Arena_%285986632567%29.jpg/960px-Colosseum_Arena_%285986632567%29.jpg","p":"https://commons.wikimedia.org/wiki/File:Colosseum_Arena_(5986632567).jpg","b":"Erik Drost","l":"CC BY 2.0"}
});
Object.assign(window.PHOTOS, {
"Montecatini":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Terme_tettuccio_montecatini_1.jpg/960px-Terme_tettuccio_montecatini_1.jpg","p":"https://commons.wikimedia.org/wiki/File:Terme_tettuccio_montecatini_1.jpg","b":"Michela.osteri","l":"CC BY-SA 4.0"},
"Montecatini_Funicular":{"i":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Funicolare_di_Montecatini_Terme.jpg/960px-Funicolare_di_Montecatini_Terme.jpg","p":"https://commons.wikimedia.org/wiki/File:Funicolare_di_Montecatini_Terme.jpg","b":"Minnitre","l":"CC BY-SA 4.0"}
});
