// Trip data. Money is in USD (converted at €1 = $1.1411, ECB rate 23 Sep 2026).
window.TRIP = {
  updated: "23 Sep 2026",
  stops: [
    { n:1, town:"Rome", sub:"arrival night, by Termini station", from:"Tue Sep 29", to:"Wed Sep 30", nights:1,
      lat:41.901, lon:12.500, photo:"Santa_Maria_Maggiore",
      hotel:{ name:"Cosmo GuestHouse", status:"paid", paid:154, phone:"+39 349 549 1459", email:"", access:{station:"2 min (130 m) to Roma Termini",centre:"38 min (2.8 km) to the Pantheon",grocery:"Small shops all around Termini (not measured)",kitchen:"No — tea/coffee maker only"}, url:"https://www.booking.com/hotel/it/cosmo-guesthouse.html", beds:"twin + queen, private bathroom in the room, A/C", total:154, cancel:"Non-refundable", note:"Paid €135. City tax €18 paid at check-in. Arrival 4–5 PM." },
      getThere:{ how:"Leonardo Express train, airport → Roma Termini", time:"32 min, every 15 min", cost:"$48" },
      weather:"77° / 58°F",
      houses:null },
    { n:2, town:"Castiglione del Lago", sub:"Lake Trasimeno, Umbria", from:"Wed Sep 30", to:"Mon Oct 5", nights:5,
      lat:43.127, lon:12.051, photo:"Castiglione_del_Lago",
      hotel:{ name:"Le Macerine", status:"paid", paid:759, phone:"+39 075 965 2084", email:"info@albergo-lemacerine.com", access:{station:"26 min (1.9 km) to the station",centre:"16 min (1.0 km) to the old town",grocery:"16 min to Gala supermarket",kitchen:"Kitchenette listed at the property (not confirmed in this room)"}, url:"https://www.booking.com/hotel/it/le-macerine.html", beds:"twin + queen, private bathroom in the room, A/C, breakfast included", total:759, cancel:"Non-refundable", note:"Paid €665. City tax about €30 paid at check-in. Arrival 3–4 PM (check-in from 3:30)." },
      getThere:{ how:"Regional trains, Roma Termini 11:45 → Orte 13:04, change (32 min) → Castiglione del Lago 15:24", time:"3 h 39 min, 1 change, fixed fare — no rush to book", cost:"$49" },
      weather:"73° / 56°F · 1 day in 10 over 80°F",
      houses:"7 houses for sale in and around town, $33,100 – $57,100.",
      alt:[{ name:"L'assiolo (only works with a car)", url:"https://www.booking.com/hotel/it/il-vivaio-castiglione-del-lago.html", total:396, beds:"2 bedrooms: queen / twin + full", note:"$294 cheaper, but out in the country — a 5-day automatic car (about $270–300 with fuel) cancels the saving, and there is no breakfast. Non-refundable.", access:{station:"46 min (3.4 km) to the station",centre:"1 h 11 min (5.2 km) to the old town",grocery:"41 min (3.1 km) to Eurospin",kitchen:"Yes — full kitchen"} }] },
    { n:3, town:"Montecatini Terme", sub:"Tuscany — day trips to Lucca, Pisa and Florence", from:"Mon Oct 5", to:"Sat Oct 10", nights:5,
      lat:43.8836, lon:10.7736, photo:"Montecatini",
      hotel:{ name:"Appartamento Hygge House", status:"booked", charge:"Sep 27", phone:"+39 339 768 1693", email:"", access:{station:"11 min (800 m) to Montecatini Centro station",centre:"20 min (1.5 km) to the Tettuccio spa · 26 min to the funicular",grocery:"Not measured yet",kitchen:"Yes — full kitchen and washing machine"}, url:"https://www.booking.com/hotel/it/appartamento-hygge-house.html", beds:"2 bedrooms (twin / full), 2 bathrooms, A/C, balcony", total:591, cancel:"Free until Sep 30", note:"€501.44 charged Sep 27. City tax about €15 at check-in. Arrival 2–3 PM (check-in from 2:30). Via G. B. Berghinz 25." },
      getThere:{ how:"Castiglione 11:09 → Montecatini Centro 14:00, change in Florence", time:"2 h 51 min, 1 change", cost:"$60" },
      weather:"71° / 54°F · rain about 1 day in 3",
      houses:"Serchio valley and Lunigiana (change at Lucca): Bagni di Lucca $36,500 (75 m²), Piazza al Serchio $33,100 (60 m²), Villafranca $20,500 (80 m²)." },
    { n:4, town:"Pescara", sub:"Abruzzo coast — staying in Montesilvano, next door", from:"Sat Oct 10", to:"Wed Oct 14", nights:4,
      lat:42.464, lon:14.214, photo:"Pescara",
      hotel:{ name:"Centoquindici Rooms & Suite (Montesilvano)", status:"booked", charge:"at the hotel", phone:"+39 353 489 2878", email:"info@centoquindici.com", access:{station:"3 min (200 m) to Montesilvano station · 5–12 min local train to Pescara Centrale (€1.60 each)",centre:"Montesilvano seafront; Pescara centre 12 min by train",grocery:"Not measured yet",kitchen:"No (Deluxe Triple Room)"}, url:"https://www.booking.com/hotel/it/centoquindici-rooms-amp-suite.html", beds:"twin + queen — pick \"1 twin bed and 1 queen bed\" when booking; private bathroom, A/C, balcony", total:396, cancel:"Free until Oct 8, pay at the hotel", note:"Booked 23 Sep: Deluxe Triple, room only, twin + queen requested. $395.80 incl. taxes (about €347), paid at the hotel. Free cancellation until Oct 8. Corso Umberto I 115, Montesilvano. Arrival 4–5 PM." },

      getThere:{ how:"Montecatini 08:57 → Prato (15 min change) → Bologna (65 min cushion) → Intercity → Pescara 15:59. Buy as ONE ticket.", time:"7 h, 2 changes — the longest day (Saturday)", cost:"$112" },
      weather:"69° / 56°F · rain about 1 day in 4",
      houses:"Cheapest on the mainland: Carunchio $20,500 (150 m²) and $25,100 (135 m²), Castelguidone $28,500 (90 m²), Celenza sul Trigno from $12,600, Atessa $34,200 (92 m²). By bus: Penne $17,100 – $54,800, Loreto Aprutino $53,600, Città Sant'Angelo $54,800 (145 m²)." },
    { n:5, town:"Lecce", sub:"Puglia — the heel of Italy", from:"Wed Oct 14", to:"Wed Oct 21", nights:7,
      lat:40.353, lon:18.172, photo:"Lecce",
      hotel:{ name:"L'Angolo di Oli'", status:"todo", access:{station:"37 min (2.7 km) to Lecce station — taxi for train days",centre:"22 min (1.6 km) to Piazza Sant'Oronzo",grocery:"Not measured yet",kitchen:"Not confirmed"}, url:"https://www.booking.com/hotel/it/l-39-angolo-di-oli-39.html", beds:"twin + king, private bathroom in the room, A/C", total:685, cancel:"Free until Oct 7, nothing charged until Oct 5", note:"Via dei Palumbo 10. Rated 8.5 from 74 reviews. 7 nights: $557 + 10% VAT + city tax ≈ $685. 1 room left (checked Sep 23 evening)." },
      getThere:{ how:"Intercity, Pescara → Lecce, around midday (times for Oct 14 being re-checked)", time:"about 4 h 48 min, direct", cost:"about $74" },
      weather:"72° / 60°F · rain about 1 day in 4",
      houses:"Casarano $43,400 for 115 m² (station in town). Also look in Tricase, Presicce-Acquarica and Ugento." },
    { n:6, town:"Salerno", sub:"Campania — Pompeii and Paestum", from:"Wed Oct 21", to:"Sun Oct 25", nights:4,
      lat:40.678, lon:14.765, photo:"Salerno",
      hotel:{ name:"B&B Salernoway", status:"todo", access:{station:"5 min (350 m) to Salerno station",centre:"15 min (1.0 km) to the cathedral",grocery:"2 min to Sole365 supermarket",kitchen:"Shared kitchen only"}, url:"https://www.booking.com/hotel/it/b-amp-b-salernoway.html", beds:"twin + king, private bathroom in the room, A/C, free breakfast (Genius)", total:395, cancel:"Free until Oct 20, pay at the property", note:"Triple Room with Bath: $322 + 10% VAT + city tax ≈ $395, free breakfast (Genius). Rated 7.8 from 653 reviews. 1 room left (checked Sep 23 evening)." },
      getThere:{ how:"Intercity x2, Lecce 11:35 → Salerno 17:36", time:"6 h, 1 change", cost:"$79" },
      weather:"71° / 59°F · rain about 2 days in 5",
      alt:[{ name:"B&B Luna", url:"https://www.booking.com/hotel/it/appartamento-salerno-salerno1.html", total:266, beds:"2 bedrooms, full bed each, private bathroom", note:"Cheaper and has a kitchen, but 34 min walk to the station.", access:{station:"34 min (2.4 km) to Salerno station",centre:"50 min (3.6 km) to the cathedral",grocery:"4 min to Dodecà supermarket",kitchen:"Yes — kitchen listed"}}],
      houses:"Almost nothing under $57,000 listed online around Salerno. The cheapest towns by price per m² are Eboli and Battipaglia (on the train line) — look in agency windows in person." },
    { n:7, town:"Rome", sub:"Prati, by the Vatican", from:"Sun Oct 25", to:"Sun Nov 1", nights:7,
      lat:41.917, lon:12.455, photo:"St_Peters",
      hotel:{ name:"Golden Rooms Cipro", status:"todo", access:{station:"2 min (130 m) to Cipro metro · 32 min (2.2 km) to Roma San Pietro",centre:"47 min (3.4 km) to the Pantheon — metro recommended",grocery:"Not measured yet",kitchen:"Not confirmed"}, url:"https://www.booking.com/hotel/it/golden-rooms-cipro.html", beds:"twin + queen, private bathroom in the room, A/C, balcony", total:1253, cancel:"Free until Oct 18, nothing paid in advance", note:"Via Giorgio Scalia 8. Rated 8.8 from 107 reviews. $1,109 + Rome city tax (€6 per person per night) ≈ $1,253. 1 room left (checked Sep 23 evening). (Vatican Charme&Chic sold out.)" },
      getThere:{ how:"Italo, Salerno 8:37 → Roma Termini 10:45 (price rises as seats sell)", time:"2 h 08 min, direct", cost:"$68" },
      weather:"71° / 55°F · rain about 2 days in 5",
      houses:"Segni (39 min by train): $13,700 – $54,800." }
  ],
  end:{ town:"Civitavecchia", date:"Sun Nov 1", lat:42.093, lon:11.795, photo:"Civitavecchia",
        how:"Metro or taxi to Roma San Pietro station, FL5 train to Civitavecchia (about 1 h, about $5 each), port shuttle $7 each or taxi." },
  days: [
    ["Tue Sep 29",1,"Land at 2:30 pm. Leonardo Express to Termini, 2 min walk to Cosmo GuestHouse (arrival 4–5 PM). Evening: Santa Maria Maggiore and dinner.",["Fiumicino","Santa_Maria_Maggiore"]],
    ["Wed Sep 30",2,"Slow morning in Rome. 11:45 train from Termini (change at Orte) → Castiglione del Lago 15:24. 4-min taxi or 19-min walk to Le Macerine (check-in 3:30 PM). Sunset on the lake.",["Lake_Trasimeno","Castiglione_lakefront"]],
    ["Thu Oct 1",2,"Day trip to Cortona — hill town above the lake. Train to Camucia-Cortona (12 min) and the bus up.",["Cortona","Cortona_Piazza"]],
    ["Fri Oct 2",2,"Castiglione old town: the castle (Rocca del Leone) and Palazzo della Corgna. Walk past the houses for sale. (National rail strike 11:00–14:00 today — no trains needed.)",["Castiglione_del_Lago","Rocca_del_Leone","Palazzo_della_Corgna"]],
    ["Sat Oct 3",2,"Day trip to Assisi — the Basilica of St Francis. Train via Terontola.",["Assisi","Assisi_town"]],
    ["Sun Oct 4",2,"Easy day: boat to Isola Maggiore, the fishing island in the lake (check the October boat times at the pier).",["Isola_Maggiore"]],
    ["Mon Oct 5",3,"Train Castiglione 11:09 → Montecatini Centro 14:00 (change in Florence). 11-min walk to Hygge House. Evening funicular up to Montecatini Alto.",["Montecatini","Montecatini_Funicular"]],
    ["Tue Oct 6",3,"Day trip to Lucca (28 min by train): walk the city walls, Piazza dell'Anfiteatro, Guinigi Tower, San Michele church.",["Walls_of_Lucca","Piazza_Anfiteatro","Guinigi_Tower","San_Michele_Lucca"]],
    ["Wed Oct 7",3,"Day trip to Florence (55 min direct): Uffizi Gallery (book ahead, $33 each), the Duomo, Ponte Vecchio.",["Florence_Duomo","Uffizi","Ponte_Vecchio","Palazzo_Vecchio"]],
    ["Thu Oct 8",3,"Day trip to Pisa (about 1 h 10 min, change at Lucca): Leaning Tower and cathedral square.",["Pisa","Pisa_Miracoli"]],
    ["Fri Oct 9",3,"House hunting up the Serchio valley: Bagni di Lucca and Barga (change at Lucca). Or a rest day at the spa.",["Bagni_di_Lucca","Barga"]],
    ["Sat Oct 10",4,"Long train day: Montecatini 08:57 → Pescara 15:59 (changes at Prato and Bologna, 65-min cushion at Bologna). Evening on the seafront.",["Pescara","Pescara_beach"]],
    ["Sun Oct 11",4,"Easy Sunday after the long travel day: seafront walk, beach, lunch by the sea. (Sunday trains to the coast only start at 12:16 and the last one back is 17:36 — so the Trabocchi coast moved to Monday by car.)",["Pescara_beach"]],
    ["Mon Oct 12",4,"Rental car (automatic): drive the Trabocchi coast road south (stop at a trabocco by San Vito), then inland to the cheap-house villages — Atessa, Celenza sul Trigno, Carunchio. Weekday, so agencies are open.",["Trabocco","San_Vito_Chietino","Atessa","Carunchio","Celenza"]],
    ["Tue Oct 13",4,"Bus to Loreto Aprutino and Penne on the weekday timetable — hill towns with houses under budget.",["Loreto_Aprutino","Penne"]],
    ["Wed Oct 14",5,"Train to Lecce (about 4 h 48 min, direct). Evening in Piazza Sant'Oronzo.",["Piazza_Sant_Oronzo"]],
    ["Thu Oct 15",5,"Lecce: Basilica of Santa Croce, the cathedral square, the Roman amphitheatre.",["Lecce","Lecce_Amphitheatre","Lecce_Duomo"]],
    ["Fri Oct 16",5,"Day trip to Gallipoli — old town on an island, beaches.",["Gallipoli","Gallipoli_beach"]],
    ["Sat Oct 17",5,"Day trip to Otranto — castle, sea walls and the cathedral's giant floor mosaic.",["Otranto","Otranto_Castle","Otranto_Cathedral"]],
    ["Sun Oct 18",5,"Easy Sunday — rest, or the beach at Gallipoli.",["Gallipoli_beach"]],
    ["Mon Oct 19",5,"House hunting: Casarano by train (houses $40,000–57,000 in town).",["Casarano"]],
    ["Tue Oct 20",5,"House hunting: Galatina or Nardò, or Tricase/Ugento.",[]],
    ["Wed Oct 21",6,"Train to Salerno, 11:35 → 17:36, 1 change. Evening on the seafront promenade.",["Salerno","Salerno_Lungomare"]],
    ["Thu Oct 22",6,"Pompeii — book ahead ($23 each; open 9 am – 7:30 pm, last entry 6 pm). About 40 min by train.",["Pompeii","Pompeii_Forum"]],
    ["Fri Oct 23",6,"Paestum — Greek temples ($17 each, no booking). 30 min by train.",["Paestum","Paestum_Neptune"]],
    ["Sat Oct 24",6,"Salerno old town: cathedral, Minerva medieval garden, seafront.",["Salerno_Cathedral","Giardino_della_Minerva"]],
    ["Sun Oct 25",7,"Italo train to Rome, 8:37 → 10:45. Afternoon walk to Castel Sant'Angelo.",["Castel_Sant_Angelo"]],
    ["Mon Oct 26",7,"Colosseum, Roman Forum and Palatine Hill ($21 each — tickets open about Sep 26).",["Colosseum","Colosseum_inside","Roman_Forum"]],
    ["Tue Oct 27",7,"Vatican Museums and Sistine Chapel — official 8 am guided tour ($137 for 3), then St Peter's. Day not picked yet: Tue 27, Wed 28 or Thu 29.",["Vatican_Museums","Vatican_Stairs","Sistine_Chapel","St_Peters"]],
    ["Wed Oct 28",7,"Pantheon, Piazza Navona, Trevi Fountain, Spanish Steps.",["Pantheon","Piazza_Navona","Trevi_Fountain","Spanish_Steps"]],
    ["Thu Oct 29",7,"Borghese Gallery (timed ticket, opens about Oct 19) and the Villa Borghese park.",["Galleria_Borghese","Villa_Borghese"]],
    ["Fri Oct 30",7,"House hunting in Segni (train, 39 min) — or a free day.",[]],
    ["Sat Oct 31",7,"Trastevere and Santa Maria in Trastevere. Pack.",["Trastevere"]],
    ["Sun Nov 1",0,"Taxi to Roma San Pietro, FL5 train to Civitavecchia, board the ship.",["Civitavecchia"]]
  ],
  car:{ what:"Peugeot 208 automatic (Sicily By Car, via DiscoverCars)", where:"Pescara Airport, about 3 km from the station", price:45, full:95,
        note:"Free cancellation, unlimited km. A full 24 h costs the same as the day. Fuel and tolls about $40 – 50. Automatic cars are scarce in Italy — book early." },
  costs:[
    ["Hotels, 33 nights (with taxes; unbooked ones estimated)",4233,"booked + live prices, 23 Sep"],
    ["City tax still due at Cosmo and Le Macerine",55,"from the confirmations"],
    ["Trains between towns + port shuttle",546,"live fares, 23 Sep"],
    ["Day-trip trains and buses",419,"estimate"],
    ["Rental car day (automatic) + fuel + tolls",90,"live price + estimate"],
    ["Sightseeing tickets",479,"official prices"],
    ["Local taxis, Rome metro and buses",125,"estimate"]
  ],
  tickets:[
    ["Colosseum + Forum + Palatine","Mon Oct 26",62,"Opens about Sep 26 on ticketing.colosseo.it"],
    ["Vatican Museums — official guided tour, 8 am","Oct 27, 28 or 29",137,"Book now on tickets.museivaticani.va"],
    ["Uffizi, Florence","Thu Oct 8",99,"Book now on uffizi.it"],
    ["Borghese Gallery","Thu Oct 29",62,"Opens about Oct 19"],
    ["Pompeii","Thu Oct 22",68,"Book now on pompeiisites.org"],
    ["Paestum","Fri Oct 23",51,"Buy at the gate"]
  ]
};
