// Trip data. Money is in USD (converted at €1 = $1.1411, ECB rate 23 Sep 2026).
window.TRIP = {
  updated: "23 Sep 2026",
  stops: [
    { n:1, town:"Rome", sub:"arrival night, by Termini station", from:"Tue Sep 29", to:"Wed Sep 30", nights:1,
      lat:41.901, lon:12.500, photo:"Santa_Maria_Maggiore",
      hotel:{ name:"Cosmo GuestHouse", status:"paid", paid:154, phone:"+39 349 549 1459", access:{station:"2 min (130 m) to Roma Termini",centre:"38 min (2.8 km) to the Pantheon",grocery:"Small shops all around Termini (not measured)",kitchen:"No — tea/coffee maker only"}, url:"https://www.booking.com/hotel/it/cosmo-guesthouse.html", beds:"twin + queen, private bathroom in the room, A/C", total:154, cancel:"Non-refundable", note:"Paid €135. City tax €18 paid at check-in. Arrival 4–5 PM." },
      getThere:{ how:"Leonardo Express train, airport → Roma Termini", time:"32 min, every 15 min", cost:"$48" },
      weather:"77° / 58°F",
      houses:null },
    { n:2, town:"Castiglione del Lago", sub:"Lake Trasimeno, Umbria", from:"Wed Sep 30", to:"Mon Oct 5", nights:5,
      lat:43.127, lon:12.051, photo:"Castiglione_del_Lago",
      hotel:{ name:"Le Macerine", status:"todo", access:{station:"26 min (1.9 km) to the station",centre:"16 min (1.0 km) to the old town",grocery:"16 min to Gala supermarket",kitchen:"Kitchenette listed at the property (not confirmed in this room)"}, url:"https://www.booking.com/hotel/it/le-macerine.html", beds:"twin + queen, private bathroom in the room, A/C, breakfast included", total:692, cancel:"Check on the page", note:"Rated 9.1 from 650 reviews. Walkable — no car needed." },
      getThere:{ how:"Regional trains, Roma Termini 11:45 → Orte 13:04, change (32 min) → Castiglione del Lago 15:24", time:"3 h 39 min, 1 change, fixed fare — no rush to book", cost:"$49" },
      weather:"73° / 56°F · 1 day in 10 over 80°F",
      houses:"7 houses for sale in and around town, $33,100 – $57,100.",
      alt:[{ name:"L'assiolo (only works with a car)", url:"https://www.booking.com/hotel/it/il-vivaio-castiglione-del-lago.html", total:396, beds:"2 bedrooms: queen / twin + full", note:"$294 cheaper, but out in the country — a 5-day automatic car (about $270–300 with fuel) cancels the saving, and there is no breakfast. Non-refundable.", access:{station:"46 min (3.4 km) to the station",centre:"1 h 11 min (5.2 km) to the old town",grocery:"41 min (3.1 km) to Eurospin",kitchen:"Yes — full kitchen"} }] },
    { n:3, town:"Lucca", sub:"Tuscany — day trips to Pisa and Florence", from:"Mon Oct 5", to:"Sun Oct 11", nights:6,
      lat:43.843, lon:10.505, photo:"Lucca",
      hotel:{ name:"Casa Jole", status:"todo", access:{station:"18 min (1.3 km) to Lucca station",centre:"10 min (750 m) to Piazza San Michele — inside the walls",grocery:"Not measured yet",kitchen:"Apartment — kitchen not yet confirmed"}, url:"https://www.booking.com/searchresults.html?ss=Casa+Jole+Lucca", beds:"queen + twin, private bathroom in the room, A/C", total:791, cancel:"Free until Oct 4", note:"Via della Zecca 58, 1st floor, inside the city walls. Rated 9.2 from 11 reviews." },
      getThere:{ how:"Regional trains, Castiglione 11:09 → Lucca 14:29", time:"3 h 20 min, 1 change", cost:"$70" },
      weather:"71° / 54°F · rain about 1 day in 3",
      alt:[{ name:"Casa Luana San Concordio", url:"https://www.booking.com/hotel/it/casa-luana-san-concordio-affitti-brevi-italia.html", total:561, beds:"queen room + bunk-bed room, private bathroom", note:"Cheaper option, outside the walls.", access:{station:"17 min (1.2 km) to Lucca station",centre:"21 min (1.5 km) to Piazza San Michele",grocery:"2 min to Esselunga",kitchen:"Yes — oven and stovetop"}}],
      houses:"Serchio valley and Lunigiana by train: Bagni di Lucca $36,500 (75 m²), Piazza al Serchio $33,100 (60 m²), Villafranca $20,500 (80 m²)." },
    { n:4, town:"Pescara", sub:"Abruzzo coast", from:"Sun Oct 11", to:"Thu Oct 15", nights:4,
      lat:42.464, lon:14.214, photo:"Pescara",
      hotel:{ name:"Alice al Mare", status:"todo", access:{station:"12 min (900 m) to Pescara Centrale",centre:"10 min (750 m) to Piazza della Rinascita",grocery:"Not measured yet",kitchen:"Apartment — kitchen not yet confirmed"}, url:"https://www.booking.com/searchresults.html?ss=Alice+al+Mare+Pescara", beds:"twin + queen apartment, private bathroom in the room, A/C", total:370, cancel:"Free until Oct 4 ($340 if non-refundable)", note:"Via Fedele Romani 19. Rated 9.7 from 45 reviews." },
      getThere:{ how:"Regional + Intercity, Lucca 9:31 → Pescara 16:31 (faster Frecciarossa: 9:31 → 15:44 for $241)", time:"7 h, 2 changes — the longest day", cost:"$116" },
      weather:"69° / 56°F · rain about 1 day in 4",
      houses:"Cheapest on the mainland: Carunchio $20,500 (150 m²) and $25,100 (135 m²), Castelguidone $28,500 (90 m²), Celenza sul Trigno from $12,600, Atessa $34,200 (92 m²). By bus: Penne $17,100 – $54,800, Loreto Aprutino $53,600, Città Sant'Angelo $54,800 (145 m²)." },
    { n:5, town:"Lecce", sub:"Puglia — the heel of Italy", from:"Thu Oct 15", to:"Wed Oct 21", nights:6,
      lat:40.353, lon:18.172, photo:"Lecce",
      hotel:{ name:"L'Angolo di Oli'", status:"todo", access:{station:"37 min (2.7 km) to Lecce station — taxi for train days",centre:"22 min (1.6 km) to Piazza Sant'Oronzo",grocery:"Not measured yet",kitchen:"Not confirmed"}, url:"https://www.booking.com/searchresults.html?ss=L%27Angolo+di+Oli+Lecce", beds:"twin + king, private bathroom in the room, A/C", total:475, cancel:"Free until Oct 8", note:"Via dei Palumbo 10. Rated 8.5 from 74 reviews." },
      getThere:{ how:"Intercity, Pescara 12:03 → Lecce 16:51", time:"4 h 48 min, direct", cost:"$74" },
      weather:"72° / 60°F · rain about 1 day in 4",
      houses:"Casarano $43,400 for 115 m² (station in town). Also look in Tricase, Presicce-Acquarica and Ugento." },
    { n:6, town:"Salerno", sub:"Campania — Pompeii and Paestum", from:"Wed Oct 21", to:"Sun Oct 25", nights:4,
      lat:40.678, lon:14.765, photo:"Salerno",
      hotel:{ name:"B&B Salernoway", status:"todo", access:{station:"5 min (350 m) to Salerno station",centre:"15 min (1.0 km) to the cathedral",grocery:"2 min to Sole365 supermarket",kitchen:"Shared kitchen only"}, url:"https://www.booking.com/hotel/it/b-amp-b-salernoway.html", beds:"twin + king, private bathroom in the room, A/C, free breakfast (Genius)", total:324, cancel:"Free until Oct 20, pay at the property", note:"Only 1 of these rooms left when checked. Rated 7.8 from 653 reviews." },
      getThere:{ how:"Intercity x2, Lecce 11:35 → Salerno 17:36", time:"6 h, 1 change", cost:"$79" },
      weather:"71° / 59°F · rain about 2 days in 5",
      alt:[{ name:"B&B Luna", url:"https://www.booking.com/hotel/it/appartamento-salerno-salerno1.html", total:266, beds:"2 bedrooms, full bed each, private bathroom", note:"Cheaper and has a kitchen, but 34 min walk to the station.", access:{station:"34 min (2.4 km) to Salerno station",centre:"50 min (3.6 km) to the cathedral",grocery:"4 min to Dodecà supermarket",kitchen:"Yes — kitchen listed"}}],
      houses:"Almost nothing under $57,000 listed online around Salerno. The cheapest towns by price per m² are Eboli and Battipaglia (on the train line) — look in agency windows in person." },
    { n:7, town:"Rome", sub:"Prati, by the Vatican", from:"Sun Oct 25", to:"Sun Nov 1", nights:7,
      lat:41.917, lon:12.455, photo:"St_Peters",
      hotel:{ name:"Golden Rooms Cipro", status:"todo", access:{station:"2 min (130 m) to Cipro metro · 32 min (2.2 km) to Roma San Pietro",centre:"47 min (3.4 km) to the Pantheon — metro recommended",grocery:"Not measured yet",kitchen:"Not confirmed"}, url:"https://www.booking.com/searchresults.html?ss=GOLDEN+ROOMS+Cipro+Rome", beds:"twin + queen, private bathroom in the room, A/C, balcony", total:1113, cancel:"Free until Oct 18", note:"Via Giorgio Scalia 8. Rated 8.8 from 107 reviews. (Vatican Charme&Chic sold out.)" },
      getThere:{ how:"Italo, Salerno 8:37 → Roma Termini 10:45 (price rises as seats sell)", time:"2 h 08 min, direct", cost:"$68" },
      weather:"71° / 55°F · rain about 2 days in 5",
      houses:"Segni (39 min by train): $13,700 – $54,800." }
  ],
  end:{ town:"Civitavecchia", date:"Sun Nov 1", lat:42.093, lon:11.795, photo:"Civitavecchia",
        how:"Metro or taxi to Roma San Pietro station, FL5 train to Civitavecchia (about 1 h, about $5 each), port shuttle $7 each or taxi." },
  days: [
    ["Tue Sep 29",1,"Land at 2:30 pm. Leonardo Express to Termini, 2 min walk to Cosmo GuestHouse (arrival 4–5 PM). Evening: Santa Maria Maggiore and dinner.",["Fiumicino","Santa_Maria_Maggiore"]],
    ["Wed Sep 30",2,"Slow morning in Rome. 11:45 train from Termini (change at Orte) → Castiglione del Lago 15:24. 4-min taxi or 19-min walk to Le Macerine (check-in 3:30 PM). Sunset on the lake.",["Lake_Trasimeno","Castiglione_lakefront"]],
    ["Thu Oct 1",2,"Castiglione old town: the castle (Rocca del Leone) and Palazzo della Corgna. Walk past the houses for sale.",["Castiglione_del_Lago","Rocca_del_Leone","Palazzo_della_Corgna"]],
    ["Fri Oct 2",2,"Day trip to Cortona — hill town above the lake. Train to Camucia-Cortona (12 min) and the bus up.",["Cortona","Cortona_Piazza"]],
    ["Sat Oct 3",2,"Day trip to Assisi — the Basilica of St Francis. Train via Terontola.",["Assisi","Assisi_town"]],
    ["Sun Oct 4",2,"Easy day: boat to Isola Maggiore, the fishing island in the lake (check the October boat times at the pier).",["Isola_Maggiore"]],
    ["Mon Oct 5",3,"Train to Lucca, 11:09 → 14:29. Evening walk on top of the city walls.",["Walls_of_Lucca"]],
    ["Tue Oct 6",3,"Lucca: Piazza dell'Anfiteatro, the Guinigi Tower with trees on top, San Michele church.",["Piazza_Anfiteatro","Guinigi_Tower","San_Michele_Lucca","Lucca_Cathedral"]],
    ["Wed Oct 7",3,"Day trip to Pisa — Leaning Tower and cathedral square (about 30 min by train).",["Pisa","Pisa_Miracoli"]],
    ["Thu Oct 8",3,"Day trip to Florence: Uffizi Gallery (book ahead, $33 each), the Duomo, Ponte Vecchio.",["Florence_Duomo","Uffizi","Ponte_Vecchio","Palazzo_Vecchio"]],
    ["Fri Oct 9",3,"House hunting up the Serchio valley by train: Bagni di Lucca and Barga.",["Bagni_di_Lucca","Barga"]],
    ["Sat Oct 10",3,"Free day in Lucca — market, bike the walls, rest before the long train day.",["Lucca"]],
    ["Sun Oct 11",4,"Long train day to Pescara: 9:31 → 16:31, 2 changes. Evening on the seafront.",["Pescara","Pescara_beach"]],
    ["Mon Oct 12",4,"Trabocchi Coast: train to San Vito Chietino (27 min) — old wooden fishing platforms over the sea.",["Trabocco","San_Vito_Chietino"]],
    ["Tue Oct 13",4,"Rental car (automatic): cheap-house villages — Atessa, Celenza sul Trigno, Carunchio. About 4 – 5 h of driving for all five villages; 3 villages is easier.",["Atessa","Carunchio","Celenza"]],
    ["Wed Oct 14",4,"Bus to Loreto Aprutino and Penne — hill towns with houses under budget.",["Loreto_Aprutino","Penne"]],
    ["Thu Oct 15",5,"Train to Lecce, 12:03 → 16:51, direct. Evening in Piazza Sant'Oronzo.",["Piazza_Sant_Oronzo"]],
    ["Fri Oct 16",5,"Lecce: Basilica of Santa Croce, the cathedral square, the Roman amphitheatre.",["Lecce","Lecce_Amphitheatre","Lecce_Duomo"]],
    ["Sat Oct 17",5,"Day trip to Gallipoli — old town on an island, beaches.",["Gallipoli","Gallipoli_beach"]],
    ["Sun Oct 18",5,"Day trip to Otranto — castle, sea walls and the cathedral's giant floor mosaic.",["Otranto","Otranto_Castle","Otranto_Cathedral"]],
    ["Mon Oct 19",5,"House hunting: Casarano by train, then Tricase or Ugento.",["Casarano"]],
    ["Tue Oct 20",5,"Free day — back to the beach at Gallipoli, or rest in Lecce.",["Gallipoli_beach"]],
    ["Wed Oct 21",6,"Train to Salerno, 11:35 → 17:36, 1 change. Evening on the seafront promenade.",["Salerno","Salerno_Lungomare"]],
    ["Thu Oct 22",6,"Pompeii — book ahead ($23 each; open 9 am – 7:30 pm, last entry 6 pm). About 40 min by train.",["Pompeii","Pompeii_Forum"]],
    ["Fri Oct 23",6,"Paestum — Greek temples ($17 each, no booking). 30 min by train.",["Paestum","Paestum_Neptune"]],
    ["Sat Oct 24",6,"Salerno old town: cathedral, Minerva medieval garden, seafront.",["Salerno_Cathedral","Giardino_della_Minerva"]],
    ["Sun Oct 25",7,"Italo train to Rome, 8:37 → 10:45. Afternoon walk to Castel Sant'Angelo.",["Castel_Sant_Angelo"]],
    ["Mon Oct 26",7,"Colosseum, Roman Forum and Palatine Hill ($21 each — tickets open about Sep 26).",["Colosseum","Colosseum_inside","Roman_Forum"]],
    ["Tue Oct 27",7,"Vatican Museums and Sistine Chapel — official 8 am guided tour ($137 for 3), then St Peter's. Day not picked yet: Tue 27, Wed 28 or Thu 29.",["Vatican_Museums","Vatican_Stairs","Sistine_Chapel","St_Peters"]],
    ["Wed Oct 28",7,"Pantheon, Piazza Navona, Trevi Fountain, Spanish Steps.",["Pantheon","Piazza_Navona","Trevi_Fountain","Spanish_Steps"]],
    ["Thu Oct 29",7,"Borghese Gallery (timed ticket, opens about Oct 19) and the Villa Borghese park.",["Galleria_Borghese","Villa_Borghese"]],
    ["Fri Oct 30",7,"House hunting in Segni (train, 39 min) — or a free day.",[]],
    ["Sat Oct 31",7,"Trastevere and Santa Maria in Trastevere. Pack.",["Trastevere"]],
    ["Sun Nov 1",0,"Taxi to Roma San Pietro, FL5 train to Civitavecchia, board the ship.",["Civitavecchia"]]
  ],
  car:{ what:"Peugeot 208 automatic (Sicily By Car, via DiscoverCars)", where:"Pescara Airport, about 3 km from the station", price:45, full:95,
        note:"Free cancellation, unlimited km. A full 24 h costs the same as the day. Fuel and tolls about $40 – 50. Automatic cars are scarce in Italy — book early." },
  costs:[
    ["Hotels, 33 nights",3919,"verified on Booking.com"],
    ["Hotel city tax + VAT (paid at hotels)",580,"estimate"],
    ["Trains between towns + port shuttle",541,"live fares, 23 Sep"],
    ["Day-trip trains and buses",419,"estimate"],
    ["Rental car day (automatic) + fuel + tolls",90,"live price + estimate"],
    ["Sightseeing tickets",479,"official prices"],
    ["Local taxis, Rome metro and buses",125,"estimate"]
  ],
  tickets:[
    ["Colosseum + Forum + Palatine","Mon Oct 26",62,"Opens about Sep 26 on ticketing.colosseo.it"],
    ["Vatican Museums — official guided tour, 8 am","Oct 27, 28 or 29",137,"Book now on tickets.museivaticani.va"],
    ["Uffizi, Florence","Thu Oct 8",99,"Book now on uffizi.it"],
    ["Borghese Gallery","Thu Oct 29",62,"Opens about Oct 19"],
    ["Pompeii","Thu Oct 22",68,"Book now on pompeiisites.org"],
    ["Paestum","Fri Oct 23",51,"Buy at the gate"]
  ]
};
