// Trip data. Money is in USD (converted at €1 = $1.1411, ECB rate 23 Sep 2026).
window.TRIP = {
  updated: "23 Sep 2026",
  stops: [
    { n:1, town:"Rome", sub:"arrival night, by Termini station", from:"Tue Sep 29", to:"Wed Sep 30", nights:1,
      lat:41.901, lon:12.500, photo:"Santa_Maria_Maggiore",
      hotel:{ name:"Parenti B&B", url:"https://www.booking.com/searchresults.html?ss=Parenti+B%26B+Roma", beds:"twin + king, elevator", total:87, note:"Non-refundable. 3 min walk from Termini. Rated 6.2 — fine for one night." },
      getThere:{ how:"Leonardo Express train, airport → Roma Termini", time:"32 min, every 15 min", cost:"$16 each" },
      weather:"77° / 58°F",
      houses:null },
    { n:2, town:"Castiglione del Lago", sub:"Lake Trasimeno, Umbria", from:"Wed Sep 30", to:"Mon Oct 5", nights:5,
      lat:43.127, lon:12.051, photo:"Castiglione_del_Lago",
      hotel:{ name:"L'assiolo", url:"https://www.booking.com/hotel/it/il-vivaio-castiglione-del-lago.html", beds:"2 bedrooms: queen / twin + full", total:396, note:"Non-refundable. 3 km outside town — taxi from the station." },
      getThere:{ how:"Train, Roma Termini → Castiglione del Lago", time:"about 2 h, direct", cost:"checking live fares" },
      weather:"73° / 56°F · 1 day in 10 over 80°F",
      houses:"7 houses for sale in and around town, $33,100 – $57,100." },
    { n:3, town:"Lucca", sub:"Tuscany — day trips to Pisa and Florence", from:"Mon Oct 5", to:"Sun Oct 11", nights:6,
      lat:43.843, lon:10.505, photo:"Lucca",
      hotel:{ name:"Lucca Arancio", url:"https://www.booking.com/hotel/it/lucca-arancio.html", beds:"twin + full", total:587, note:"Free cancel until Sep 28. About 1.6 mi from the old town — a closer option is being checked." },
      getThere:{ how:"Train via Florence (change at Firenze S.M.N.)", time:"about 2 h 40 min", cost:"checking live fares" },
      weather:"71° / 54°F · rain about 1 day in 3",
      houses:"Serchio valley and Lunigiana by train: Bagni di Lucca $36,500 (75 m²), Piazza al Serchio $33,100 (60 m²), Villafranca $20,500 (80 m²)." },
    { n:4, town:"Pescara", sub:"Abruzzo coast", from:"Sun Oct 11", to:"Thu Oct 15", nights:4,
      lat:42.464, lon:14.214, photo:"Pescara",
      hotel:{ name:"B&B Sofia", url:"https://www.booking.com/hotel/it/sofia-b.html", beds:"twin + queen", total:280, note:"Non-refundable, paid by bank transfer before arrival. 0.7 mi from the station." },
      getThere:{ how:"Train, Lucca → Florence → Bologna → Pescara", time:"about 5 – 6 h", cost:"checking live fares" },
      weather:"69° / 56°F · rain about 1 day in 4",
      houses:"Cheapest on the mainland: Carunchio $20,500 (150 m²) and $25,100 (135 m²), Castelguidone $28,500 (90 m²), Celenza sul Trigno from $12,600, Atessa $34,200 (92 m²). By bus: Penne $17,100 – $54,800, Loreto Aprutino $53,600, Città Sant'Angelo $54,800 (145 m²)." },
    { n:5, town:"Lecce", sub:"Puglia — the heel of Italy", from:"Thu Oct 15", to:"Wed Oct 21", nights:6,
      lat:40.353, lon:18.172, photo:"Lecce",
      hotel:{ name:"Dimora Rudiae", url:"https://www.booking.com/hotel/it/dimora-rudiae-lecce.html", beds:"twin + queen", total:476, note:"Free cancel until Oct 10. 3rd floor (stairs). 12 min walk to Piazza Sant'Oronzo, 13 min to the station." },
      getThere:{ how:"Train, Pescara → Lecce", time:"about 4 h, direct", cost:"checking live fares" },
      weather:"72° / 60°F · rain about 1 day in 4",
      houses:"Casarano $43,400 for 115 m² (station in town). Also look in Tricase, Presicce-Acquarica and Ugento." },
    { n:6, town:"Salerno", sub:"Campania — Pompeii and Paestum", from:"Wed Oct 21", to:"Sun Oct 25", nights:4,
      lat:40.678, lon:14.765, photo:"Salerno",
      hotel:{ name:"B&B Luna", url:"https://www.booking.com/hotel/it/appartamento-salerno-salerno1.html", beds:"2 bedrooms, full bed each", total:266, note:"Free cancel until Oct 16. Host must approve. 33 min walk to the station — a closer option is being checked." },
      getThere:{ how:"Train, Lecce → Salerno (1 change)", time:"about 5 h 30 min – 6 h 30 min", cost:"checking live fares" },
      weather:"71° / 59°F · rain about 2 days in 5",
      houses:"Almost nothing under $57,000 listed online around Salerno. The cheapest towns by price per m² are Eboli and Battipaglia (on the train line) — look in agency windows in person." },
    { n:7, town:"Rome", sub:"Prati, by the Vatican", from:"Sun Oct 25", to:"Sun Nov 1", nights:7,
      lat:41.917, lon:12.455, photo:"St_Peters",
      hotel:{ name:"Vatican Charme&Chic", url:"https://www.booking.com/hotel/it/vatican-charme-amp-chic.html", beds:"twin + queen, elevator", total:914, note:"Free cancel until Oct 20. 18 min walk to the Vatican Museums, 14 min to Ottaviano metro." },
      getThere:{ how:"Train, Salerno → Roma Termini (Frecciarossa or Italo)", time:"about 2 h 30 min", cost:"checking live fares" },
      weather:"71° / 55°F · rain about 2 days in 5",
      houses:"Segni (39 min by train): $13,700 – $54,800." }
  ],
  end:{ town:"Civitavecchia", date:"Sun Nov 1", lat:42.093, lon:11.795, photo:"Civitavecchia",
        how:"Taxi to Roma San Pietro station, FL5 train to Civitavecchia (about 1 h, about $5 each), port shuttle $7 each or taxi." },
  days: [
    ["Tue Sep 29",1,"Land at 2:30 pm. Leonardo Express to Termini, check in. Evening: Santa Maria Maggiore (3 min walk) and dinner.",["Fiumicino","Santa_Maria_Maggiore"]],
    ["Wed Sep 30",2,"Train to Castiglione del Lago (about 2 h). Taxi to the house. Sunset on the lake.",["Lake_Trasimeno"]],
    ["Thu Oct 1",2,"Castiglione old town: the castle (Rocca del Leone) and Palazzo della Corgna. Walk past the houses for sale.",["Castiglione_del_Lago"]],
    ["Fri Oct 2",2,"Day trip to Cortona — hill town above the lake. Train to Camucia-Cortona (12 min) and the bus up.",["Cortona"]],
    ["Sat Oct 3",2,"Day trip to Assisi — the Basilica of St Francis. Train via Terontola.",["Assisi"]],
    ["Sun Oct 4",2,"Easy day: boat to Isola Maggiore, the fishing island in the lake (check the October boat times at the pier).",["Isola_Maggiore"]],
    ["Mon Oct 5",3,"Train to Lucca via Florence. Evening walk on top of the city walls.",["Walls_of_Lucca"]],
    ["Tue Oct 6",3,"Lucca: Piazza dell'Anfiteatro, the Guinigi Tower with trees on top, San Michele church.",["Piazza_Anfiteatro","Guinigi_Tower"]],
    ["Wed Oct 7",3,"Day trip to Pisa — Leaning Tower and cathedral square (about 30 min by train).",["Pisa"]],
    ["Thu Oct 8",3,"Day trip to Florence: Uffizi Gallery (book ahead, $33 each), the Duomo, Ponte Vecchio.",["Florence_Duomo","Uffizi","Ponte_Vecchio"]],
    ["Fri Oct 9",3,"House hunting up the Serchio valley by train: Bagni di Lucca and Barga.",["Bagni_di_Lucca","Barga"]],
    ["Sat Oct 10",3,"Free day in Lucca — market, bike the walls, rest before the long train day.",["Lucca"]],
    ["Sun Oct 11",4,"Long train day to Pescara (about 5 – 6 h). Evening on the seafront.",["Pescara"]],
    ["Mon Oct 12",4,"Trabocchi Coast: train to San Vito Chietino (27 min) — old wooden fishing platforms over the sea.",["Trabocco","San_Vito_Chietino"]],
    ["Tue Oct 13",4,"Rental car (automatic): cheap-house villages — Atessa, Celenza sul Trigno, Carunchio. About 4 – 5 h of driving for all five villages; 3 villages is easier.",["Atessa","Carunchio","Celenza"]],
    ["Wed Oct 14",4,"Bus to Loreto Aprutino and Penne — hill towns with houses under budget.",["Loreto_Aprutino","Penne"]],
    ["Thu Oct 15",5,"Train to Lecce (about 4 h, direct). Evening in Piazza Sant'Oronzo.",["Piazza_Sant_Oronzo"]],
    ["Fri Oct 16",5,"Lecce: Basilica of Santa Croce, the cathedral square, the Roman amphitheatre.",["Lecce"]],
    ["Sat Oct 17",5,"Day trip to Gallipoli — old town on an island, beaches.",["Gallipoli"]],
    ["Sun Oct 18",5,"Day trip to Otranto — castle, sea walls and the cathedral's giant floor mosaic.",["Otranto","Otranto_Cathedral"]],
    ["Mon Oct 19",5,"House hunting: Casarano by train, then Tricase or Ugento.",["Casarano"]],
    ["Tue Oct 20",5,"Free day — back to the beach at Gallipoli, or rest in Lecce.",["Gallipoli"]],
    ["Wed Oct 21",6,"Train to Salerno (about 5 h 30 min – 6 h 30 min, 1 change). Evening on the seafront promenade.",["Salerno"]],
    ["Thu Oct 22",6,"Pompeii — book ahead ($23 each; open 9 am – 7:30 pm, last entry 6 pm). About 40 min by train.",["Pompeii"]],
    ["Fri Oct 23",6,"Paestum — Greek temples ($17 each, no booking). 30 min by train.",["Paestum"]],
    ["Sat Oct 24",6,"Salerno old town: cathedral, Minerva medieval garden, seafront.",["Salerno_Cathedral","Giardino_della_Minerva"]],
    ["Sun Oct 25",7,"Train to Rome (about 2 h 30 min). Evening walk to Castel Sant'Angelo.",["Castel_Sant_Angelo"]],
    ["Mon Oct 26",7,"Colosseum, Roman Forum and Palatine Hill ($21 each — tickets open about Sep 26).",["Colosseum","Roman_Forum"]],
    ["Tue Oct 27",7,"Vatican Museums and Sistine Chapel — official 8 am guided tour ($137 for 3), then St Peter's. Day not picked yet: Tue 27, Wed 28 or Thu 29.",["Vatican_Museums","Sistine_Chapel","St_Peters"]],
    ["Wed Oct 28",7,"Pantheon, Piazza Navona, Trevi Fountain, Spanish Steps.",["Pantheon","Piazza_Navona","Trevi_Fountain","Spanish_Steps"]],
    ["Thu Oct 29",7,"Borghese Gallery (timed ticket, opens about Oct 19) and the Villa Borghese park.",["Galleria_Borghese"]],
    ["Fri Oct 30",7,"House hunting in Segni (train, 39 min) — or a free day.",[]],
    ["Sat Oct 31",7,"Trastevere and Santa Maria in Trastevere. Pack.",["Trastevere"]],
    ["Sun Nov 1",0,"Taxi to Roma San Pietro, FL5 train to Civitavecchia, board the ship.",["Civitavecchia"]]
  ],
  car:{ what:"Peugeot 208 automatic (Sicily By Car, via DiscoverCars)", where:"Pescara Airport, about 3 km from the station", price:45, full:95,
        note:"Free cancellation, unlimited km. A full 24 h costs the same as the day. Fuel and tolls about $40 – 50. Automatic cars are scarce in Italy — book early." },
  tickets:[
    ["Colosseum + Forum + Palatine","Mon Oct 26",62,"Opens about Sep 26 on ticketing.colosseo.it"],
    ["Vatican Museums — official guided tour, 8 am","Oct 27, 28 or 29",137,"Book now on tickets.museivaticani.va"],
    ["Uffizi, Florence","Thu Oct 8",99,"Book now on uffizi.it"],
    ["Borghese Gallery","Thu Oct 29",62,"Opens about Oct 19"],
    ["Pompeii","Thu Oct 22",68,"Book now on pompeiisites.org"],
    ["Paestum","Fri Oct 23",51,"Buy at the gate"]
  ]
};
